@extends('layouts.master')
@section('title','Source Question')
@section('content')
@php
$payload=is_array($item->payload)?$item->payload:[];$mode=$item->run->mode?:'import';$audit=is_array($item->audit_result)?$item->audit_result:[];
$renderMath=function($value){$content=app(\App\Services\MathContentNormalizer::class)->normalize((string)$value)['content'];return preg_replace('/(?<=\S)\$\$(.+?)\$\$(?=\S)/s','\\($1\\)',$content)??$content;};
@endphp
@include('partials.student-mathjax')
@component('components.breadcrumb') @slot('li_1','Academic') @slot('title',ucfirst($mode).' Question Review') @endcomponent
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="card"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-2"><a href="{{ route('source-question-import.show',$item->run) }}">&larr; Back to run #{{ $item->run_id }}</a><div><span class="badge bg-info">{{ str_replace('_',' ',$item->status) }}</span> <code>{{ $item->adapter ?: 'auto' }}</code></div></div><h4 class="mt-3">CSV row {{ $item->row_number }}</h4><a target="_blank" rel="noopener" href="{{ $item->source_url }}">Open source page</a>@if($item->question_id) · <a href="{{ route('questions.edit',$item->question_id) }}">Open existing question #{{ $item->question_id }}</a>@endif</div></div>
@if($mode==='audit')
<div class="card"><div class="card-body"><h5>Field-by-field audit</h5><p class="text-muted">Select missing or mismatched fields to repair. Blank fields are safe to fill. Replacing a nonblank mismatch requires the confirmation checkbox.</p>
@if($audit)<form method="post" action="{{ route('source-question-import.audit.repair',$item) }}">@csrf<div class="table-responsive"><table class="table align-middle"><thead><tr><th></th><th>Field</th><th>Status</th><th>Current ExamElite value</th><th>Latest scraped value</th></tr></thead><tbody>@foreach(($audit['fields']??[]) as $field=>$difference)<tr><td><input type="checkbox" name="fields[]" value="{{ $field }}" @disabled(empty($difference['repairable']))></td><td><code>{{ $field }}</code></td><td><span class="badge {{ $difference['status']==='match'?'bg-success':($difference['status']==='missing'?'bg-warning text-dark':($difference['status']==='mismatch'?'bg-danger':'bg-secondary')) }}">{{ str_replace('_',' ',$difference['status']) }}</span></td><td class="audit-value">{!! $renderMath($difference['current']??'') !!}</td><td class="audit-value">{!! $renderMath($difference['extracted']??'') !!}</td></tr>@endforeach</tbody></table></div><div class="form-check mb-3"><input type="hidden" name="confirm_overwrite" value="0"><input class="form-check-input" type="checkbox" name="confirm_overwrite" value="1" id="confirm-overwrite"><label class="form-check-label" for="confirm-overwrite">I confirm selected nonblank mismatches may be overwritten from the source page.</label></div><button class="btn btn-warning">Apply selected repairs to existing question</button></form>@else<div class="alert alert-secondary">No completed audit comparison is available.</div>@endif
</div></div>
@endif
@if($payload)<div class="card"><div class="card-body"><h5>{{ $mode==='audit'?'Latest scraper snapshot':'Extracted question' }}</h5><div class="border rounded p-3 math-content">{!! $renderMath($payload['question']??$item->question?->question??'') !!}</div><h6 class="mt-3">Options</h6><ol class="math-content">@foreach(($payload['options']??[]) as $option)<li class="mb-2">{!! $renderMath($option) !!}</li>@endforeach</ol><p><b>Answer:</b> {{ $payload['answer']??'' }} · <b>Marks:</b> {{ $payload['marks']??'' }} · <b>Negative:</b> {{ $payload['negative_marks']??'' }}</p><p><b>Adapter version:</b> {{ $payload['adapter_version']??1 }}</p>@if(!empty($payload['assignment']))<p><b>Resolved assignment (webpage overrides CSV):</b> {{ json_encode($payload['assignment']) }}</p>@endif</div></div>@endif
<style>.math-content,.audit-value{overflow-wrap:anywhere}.math-content img,.audit-value img{max-width:100%;height:auto}.audit-value{min-width:240px;max-width:480px}</style>
@endsection
