@extends('layouts.master')
@section('title','Source Question Run')
@section('content')
@component('components.breadcrumb') @slot('li_1','Academic') @slot('title',ucfirst($run->mode ?: 'import').' Run #'.$run->id) @endcomponent
@php
$mode=$run->mode ?: 'import'; $items=$run->items; $crawl=(array)data_get($run->options,'crawl',[]); $meta=fn($item,$key)=>trim((string)(($item->payload['metadata'][$key]??$item->metadata[$key]??'')?:''));
$filters=['group','exam','category','subcategory','package','subject']; foreach($filters as $filter){$value=trim((string)request($filter));if($value!=='')$items=$items->filter(fn($item)=>strcasecmp($meta($item,$filter),$value)===0);} if(request('status'))$items=$items->where('status',request('status'));
$options=[];foreach($filters as $filter)$options[$filter]=$run->items->map(fn($item)=>$meta($item,$filter))->filter()->unique()->sort()->values(); $query=request()->query();
$retryable=$mode==='audit'?['failed','audit_changes','audit_clean']:['failed','needs_review'];
@endphp
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="card mb-3"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h4 class="mb-1">{{ ucfirst($mode) }} run #{{ $run->id }} <span class="badge bg-info">{{ $run->status }}</span></h4><p class="mb-0">Adapter {{ $run->adapter ?: 'auto' }} · Processed {{ $run->processed }}/{{ $run->total }} · {{ $mode==='audit'?'Checked':'Ready' }} {{ $run->ready }} · Duplicates {{ $run->duplicates }} · Failed {{ $run->failed }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="{{ route('source-question-import.index') }}">All runs</a><a class="btn btn-outline-primary" href="{{ route('source-question-import.paper.preview',array_merge([$run],$query)) }}">View snapshots</a>@if($mode==='import')<a class="btn btn-primary" href="{{ route('source-question-import.paper.edit',array_merge([$run],$query)) }}">Edit extracted paper</a>@endif</div></div>
@if($crawl)<div class="alert alert-primary"><div><strong>Base URL discovery:</strong> {{ $crawl['base_url'] ?? '' }}</div><div class="mt-1">Pages scanned {{ $crawl['pages_scanned'] ?? 0 }}/{{ $crawl['max_pages'] ?? 0 }} &middot; Question URLs found {{ $crawl['question_urls_found'] ?? 0 }} &middot; New queued {{ $crawl['new_questions'] ?? 0 }} &middot; Existing skipped {{ $crawl['skipped_existing'] ?? 0 }} &middot; {{ !empty($crawl['discovery_complete']) ? 'Discovery complete' : 'Discovery continuing' }}</div>@if(!empty($crawl['last_error']))<div class="small text-danger mt-1">Latest page error: {{ $crawl['last_error'] }}</div>@endif</div>@endif
@if($mode==='audit')<div class="alert alert-warning mb-0 mt-3"><strong>Audit-only:</strong> this run cannot publish or create questions. Open a row to review differences and selectively repair the linked question.</div>@else<div class="alert alert-info mb-0 mt-3">URLs already present in ExamElite are marked duplicate without running the scraper. Use the Audit form to re-check them.</div>@endif</div>
<div class="card"><div class="card-body"><form method="get" class="row g-2 mb-3">@foreach(['group'=>'groups','exam'=>'exams','category'=>'categories','package'=>'packages','subject'=>'subjects'] as $filter=>$label)<div class="col-md-2"><select name="{{ $filter }}" class="form-select"><option value="">All {{ $label }}</option>@foreach($options[$filter] as $value)<option @selected(request($filter)===$value)>{{ $value }}</option>@endforeach</select></div>@endforeach<div class="col-md-2"><button class="btn btn-primary">Filter</button> <a class="btn btn-outline-secondary" href="{{ route('source-question-import.show',$run) }}">Clear</a></div></form>
<form method="post" action="{{ route('source-question-import.retry',$run) }}">@csrf<div class="d-flex justify-content-between align-items-center mb-2"><span class="small text-muted"><span id="selected-count">0</span> selected</span><button class="btn btn-sm btn-warning">Retry selected</button></div>
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th><input type="checkbox" id="select-all"></th><th>Row</th><th>Adapter</th><th>Question/source</th><th>Status</th><th>Audit summary</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td><input class="retry-check" type="checkbox" name="item_ids[]" value="{{ $item->id }}" @disabled(!in_array($item->status,$retryable,true))></td><td>{{ $item->row_number }}</td><td><code>{{ $item->adapter ?: 'auto' }}</code></td><td><div class="question-preview">{{ \Illuminate\Support\Str::limit(strip_tags((string)($item->payload['question']??$item->question?->question??'')),100) }}</div><a target="_blank" rel="noopener" href="{{ $item->source_url }}">{{ \Illuminate\Support\Str::limit($item->source_url,70) }}</a></td><td><span class="badge {{ str_contains($item->status,'clean')?'bg-success':(in_array($item->status,['failed','audit_missing'])?'bg-danger':(in_array($item->status,['duplicate','audit_changes'])?'bg-warning text-dark':'bg-info')) }}">{{ str_replace('_',' ',$item->status) }}</span>@if($item->error_message)<div class="small text-danger mt-1">{{ $item->error_message }}</div>@endif</td><td>@if(is_array($item->audit_result))@php $changed=collect($item->audit_result['fields']??[])->whereIn('status',['missing','mismatch'])->count(); @endphp{{ $changed }} field change(s)@else—@endif</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('source-question-import.item',$item) }}">{{ $mode==='audit'?'Review audit':'View' }}</a>@if($item->question_id)<a class="btn btn-sm btn-outline-secondary" href="{{ route('questions.edit',$item->question_id) }}">Question</a>@endif</td></tr>@empty<tr><td colspan="7" class="text-muted">No rows match these filters.</td></tr>@endforelse</tbody></table></div></form></div></div>
<style>.question-preview{max-width:340px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.retry-check{width:18px;height:18px}</style>
@endsection
@section('script')<script>document.addEventListener('DOMContentLoaded',()=>{const all=document.getElementById('select-all'),boxes=[...document.querySelectorAll('.retry-check:not(:disabled)')],count=document.getElementById('selected-count');const update=()=>count.textContent=boxes.filter(box=>box.checked).length;all?.addEventListener('change',()=>{boxes.forEach(box=>box.checked=all.checked);update()});boxes.forEach(box=>box.addEventListener('change',update));});</script>@endsection
