@extends('layouts.master')
@section('title', 'Image Cleanup Bot')
@section('content')
@component('components.breadcrumb') @slot('li_1', 'AI Tools') @slot('title', 'Image Cleanup Bot') @endcomponent

@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="card mb-3">
    <div class="card-header d-flex flex-wrap justify-content-between align-items-start gap-2">
        <div><h4 class="mb-1">Clean or faithfully redraw existing images</h4><div class="text-muted">Choose individual images, one complete paper, or multiple papers. Use free local cleanup for light watermark/background removal, or AI only when reconstruction is required.</div></div>
        <a href="{{ route('configurations.ai') }}" class="btn btn-sm btn-outline-primary"><i class="ri-settings-3-line me-1"></i>Admin AI Settings</a>
    </div>
    <div class="card-body">
        @if(!$configuration?->image_cleanup_enabled)
            <div class="alert alert-warning">Image Cleanup Bot is disabled. Enable it and select a provider in Admin AI Settings.</div>
        @else
            @php $provider = $configuration->image_cleanup_provider === 'google' ? 'Gemini' : 'OpenAI'; $model = $configuration->image_cleanup_provider === 'google' ? $configuration->image_cleanup_google_model : $configuration->image_cleanup_openai_model; @endphp
            <div class="alert alert-info py-2"><strong>Admin-selected provider:</strong> {{ $provider }} &middot; {{ $model }} &middot; {{ ucfirst($configuration->image_cleanup_quality ?: 'medium') }} quality. There is no automatic provider fallback.</div>
        @endif
        <form method="POST" action="{{ route('image-cleanup.store') }}" id="cleanup-form">@csrf
            <input type="hidden" name="filter_q" id="cleanup-filter-q"><input type="hidden" name="filter_group_id" id="cleanup-filter-group"><input type="hidden" name="filter_category_id" id="cleanup-filter-category"><input type="hidden" name="filter_package_id" id="cleanup-filter-package">
            <input type="hidden" name="exam_id" id="cleanup-exam-id" value="{{ old('exam_id') }}">
            <div class="row g-3">
                <div class="col-md-4"><label class="form-label">Group</label><select id="cleanup-group" class="form-select"><option value="">All groups</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->group_name }}</option>@endforeach</select></div>
                <div class="col-md-4"><label class="form-label">Category</label><select id="cleanup-category" class="form-select"><option value="">All categories</option></select></div>
                <div class="col-md-4"><label class="form-label">Package</label><select id="cleanup-package" class="form-select"><option value="">All packages</option></select></div>
                <div class="col-12">
                    <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-2"><label class="form-label mb-0" for="cleanup-exam-search">Search and select papers</label><div class="d-flex flex-wrap align-items-center gap-2"><span class="badge bg-light text-dark border">First 30 matching papers shown</span><button type="submit" class="btn btn-sm btn-primary" id="cleanup-all-filtered" name="selection_mode" value="all_filtered" disabled><i class="ri-checkbox-multiple-line me-1"></i>Select all matching papers</button></div></div>
                    <input type="search" id="cleanup-exam-search" class="form-control" placeholder="Type exam name; results respect Group, Category and Package">
                    <div id="cleanup-exam-results" class="list-group mt-2"></div>
                    <div class="small text-muted mt-1" id="cleanup-exam-note">Tick one or more papers, or open one paper to choose individual images.</div>
                </div>
                <div class="col-md-4"><label class="form-label" for="cleanup-action">Cleanup action</label><select class="form-select" name="action" id="cleanup-action"><option value="remove_image">Local: remove selected standalone logo/image (FREE)</option><option value="local_cleanup">Local: remove light watermark / scan colour (FREE)</option><option value="remove_watermark">AI: remove watermark / logo and reconstruct</option><option value="clean_enhance">AI: clean and enhance scan</option><option value="redraw">AI: faithfully redraw diagram</option></select><div class="form-text">Local actions never call an AI API. Remove-image deletes a standalone selected logo/image; pixel cleanup works best for light or semi-transparent marks on white backgrounds.</div></div>
                <div class="col-md-8"><label class="form-label">AI instruction <span class="text-muted fw-normal">(optional; ignored by local actions)</span></label><input class="form-control" name="instructions" maxlength="2000" value="{{ old('instructions') }}" placeholder="Example: watermark is diagonal; preserve all labels and arrows exactly"></div>
            </div>

            <div class="border rounded mt-4 d-none" id="cleanup-papers-panel">
                <div class="p-3 border-bottom d-flex flex-wrap justify-content-between align-items-center gap-2">
                    <div><h5 class="mb-1"><span id="cleanup-paper-count">0</span> paper(s) selected</h5><div class="small text-muted" id="cleanup-paper-cost-note">Loading image counts...</div></div>
                    <button type="button" class="btn btn-sm btn-outline-secondary" id="cleanup-clear-papers">Clear papers</button>
                </div>
                <div class="p-3 d-flex flex-wrap gap-2" id="cleanup-selected-papers"></div>
                <div class="p-3 border-top d-flex flex-wrap justify-content-between align-items-center gap-2">
                    <span class="small text-muted">A separate review run is created for each paper. Nothing changes live until you publish a draft.</span>
                    <button class="btn btn-primary" id="cleanup-all-papers" name="selection_mode" value="all_images" disabled><i class="ri-stack-line me-1"></i>Process every existing image in selected papers</button>
                </div>
            </div>

            <div class="border rounded mt-4 d-none" id="cleanup-images-panel">
                <div class="p-3 border-bottom d-flex flex-wrap justify-content-between align-items-center gap-2">
                    <div><h5 class="mb-1" id="cleanup-selected-exam"></h5><div class="small text-muted"><span id="cleanup-image-count">0</span> existing images found</div></div>
                    <div class="d-flex flex-wrap gap-2"><input type="search" class="form-control form-control-sm" id="cleanup-image-filter" placeholder="Search question, field or code" style="width:240px"><button type="button" class="btn btn-sm btn-outline-primary" id="cleanup-select-visible">Select all visible</button><button type="button" class="btn btn-sm btn-outline-secondary" id="cleanup-clear-selection">Clear images</button></div>
                </div>
                <div class="p-3"><div class="row g-3" id="cleanup-image-grid"></div></div>
                <div class="p-3 border-top d-flex flex-wrap justify-content-between align-items-center gap-2"><strong><span id="cleanup-selected-count">0</span> individual image(s) selected</strong><button class="btn btn-primary" id="cleanup-start" name="selection_mode" value="selected_images" disabled><i class="ri-magic-line me-1"></i>Process selected images only</button></div>
            </div>
        </form>
    </div>
</div>

<form method="POST" action="{{ route('image-cleanup.publish-runs') }}" id="cleanup-bulk-publish-form" class="d-none">@csrf</form>
<div class="card"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="mb-1">Cleanup history</h5><div class="small text-muted">Ready means generated and awaiting review. Administrators may publish selected or all ready drafts without a separate approval step.</div></div><div class="d-flex flex-wrap align-items-center gap-2"><label class="form-check mb-0"><input class="form-check-input" type="checkbox" id="cleanup-select-all-runs"> <span class="form-check-label">Select all visible</span></label><button class="btn btn-sm btn-success" type="submit" form="cleanup-bulk-publish-form" name="publish_scope" value="selected" id="cleanup-publish-selected-runs" disabled data-swal-confirm="Admin override: publish every ready image draft in the selected cleanup runs, even though review is pending? Previous question versions will be saved."><i class="ri-check-double-line me-1"></i>Publish selected</button><button class="btn btn-sm btn-warning" type="submit" form="cleanup-bulk-publish-form" name="publish_scope" value="all_ready" data-swal-confirm="Admin override: publish ALL ready image drafts across cleanup history, even though review is pending? Previous question versions will be saved."><i class="ri-check-double-line me-1"></i>Publish all ready</button></div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th style="width:48px"></th><th>Exam</th><th>Provider</th><th>Status</th><th>Progress</th><th>Requested</th><th></th></tr></thead><tbody>
@forelse($runs as $run)<tr><td><input class="form-check-input cleanup-run-check" type="checkbox" name="run_ids[]" value="{{ $run->id }}" form="cleanup-bulk-publish-form" aria-label="Select {{ $run->exam?->name }}" @disabled(!$run->publishable_items_count)></td><td><strong>{{ $run->exam?->name }}</strong><div class="small text-muted">{{ str_replace('_',' ',ucfirst($run->action)) }}</div>@if($run->publishable_items_count)<span class="badge bg-warning text-dark mt-1">{{ $run->publishable_items_count }} pending review</span>@endif</td><td>{{ ucfirst($run->provider) }}<div class="small text-muted">{{ $run->model }}</div></td><td><span class="badge bg-{{ $run->status==='completed'?'success':(in_array($run->status,['failed','cancelled'])?'danger':'warning') }}">{{ ucfirst(str_replace('_',' ',$run->status)) }}</span></td><td>{{ $run->processed_images }} / {{ $run->total_images }}<div class="small text-muted">{{ $run->publishable_items_count }} ready &middot; {{ $run->failed_count }} failed</div></td><td>{{ $run->created_at->format('d M Y H:i') }}<div class="small text-muted">{{ $run->requester?->name }}</div></td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-primary" href="{{ route('image-cleanup.show',$run) }}">Review</a>@if(in_array($run->status,['queued','starting','running']))<form method="POST" action="{{ route('image-cleanup.stop',$run) }}">@csrf<button class="btn btn-sm btn-danger"><i class="ri-stop-circle-line"></i> Stop</button></form>@endif</div></td></tr>
@empty<tr><td colspan="7" class="text-center text-muted py-5">No image cleanup runs yet.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">{{ $runs->links() }}</div></div>
@endsection

@section('script')
<script>
document.addEventListener('DOMContentLoaded',()=>{
 const categories=@json($categoryOptions),packages=@json($packageOptions),searchUrl=@json(route('image-cleanup.exams.search')),summaryUrl=@json(route('image-cleanup.exams.selection-summary')),imagesBase=@json(url('image-cleanup/exams'));
 const group=document.getElementById('cleanup-group'),category=document.getElementById('cleanup-category'),pkg=document.getElementById('cleanup-package'),search=document.getElementById('cleanup-exam-search'),results=document.getElementById('cleanup-exam-results'),note=document.getElementById('cleanup-exam-note'),examId=document.getElementById('cleanup-exam-id'),paperPanel=document.getElementById('cleanup-papers-panel'),paperList=document.getElementById('cleanup-selected-papers'),allPapers=document.getElementById('cleanup-all-papers'),imagePanel=document.getElementById('cleanup-images-panel'),grid=document.getElementById('cleanup-image-grid'),filter=document.getElementById('cleanup-image-filter'),start=document.getElementById('cleanup-start'),action=document.getElementById('cleanup-action');
 const selectedPapers=new Map(),imageCache=new Map(),searchExams=new Map();
 const isLocal=()=>['remove_image','local_cleanup'].includes(action.value);
 let images=[],timer=null,controller=null,matchingTotal=0,allFilteredSubmitting=false;
 const escape=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
 const refill=()=>{const gid=Number(group.value||0),cid=Number(category.value||0);category.innerHTML='<option value="">All categories</option>'+categories.filter(c=>!gid||c.group_ids.includes(gid)).map(c=>`<option value="${c.id}">${escape(c.title)}</option>`).join('');if(cid&&[...category.options].some(o=>Number(o.value)===cid))category.value=cid;const active=Number(category.value||0);pkg.innerHTML='<option value="">All packages</option>'+packages.filter(p=>(!gid||p.group_ids.includes(gid))&&(!active||p.category_id===active||p.subcategory_id===active)).map(p=>`<option value="${p.id}">${escape(p.name)}</option>`).join('');};
 const fetchImages=async id=>{id=Number(id);if(imageCache.has(id))return imageCache.get(id);const response=await fetch(`${imagesBase}/${id}/images`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Image list failed');const data=await response.json();const found=data.images||[];imageCache.set(id,found);return found;};
 const renderPaperSelection=()=>{const papers=[...selectedPapers.values()],pending=papers.some(p=>!imageCache.has(p.id)),total=papers.reduce((sum,p)=>sum+(imageCache.get(p.id)?.length||0),0);paperPanel.classList.toggle('d-none',papers.length===0);document.getElementById('cleanup-paper-count').textContent=papers.length;document.getElementById('cleanup-paper-cost-note').textContent=pending?'Loading image counts...':(isLocal()?`${total} existing image(s) = 0 paid API requests. Processed locally with PHP GD.`:`${total} existing image(s) = ${total} paid API request(s). No PDF pages are sent.`);allPapers.disabled=!papers.length||pending||total===0;paperList.innerHTML=papers.map(p=>`<span class="badge bg-light text-dark border fs-6 d-inline-flex align-items-center gap-2">${escape(p.name)} <button type="button" class="btn-close cleanup-remove-paper" data-id="${p.id}" aria-label="Remove"></button><input type="hidden" name="exam_ids[]" value="${p.id}"></span>`).join('');};
 const selectPaper=async(id,name,checked=true)=>{id=Number(id);if(checked){if(!selectedPapers.has(id)&&selectedPapers.size>=30){alert('Select at most 30 papers in one batch.');return false;}selectedPapers.set(id,{id,name});renderPaperSelection();try{await fetchImages(id);}catch(e){selectedPapers.delete(id);alert('Could not load images for '+name);}renderPaperSelection();}else{selectedPapers.delete(id);renderPaperSelection();}return true;};
 const syncFilterInputs=()=>{document.getElementById('cleanup-filter-q').value=search.value;document.getElementById('cleanup-filter-group').value=group.value;document.getElementById('cleanup-filter-category').value=category.value;document.getElementById('cleanup-filter-package').value=pkg.value;};
 const query=async()=>{controller?.abort();controller=new AbortController();syncFilterInputs();const params=new URLSearchParams({q:search.value,group_id:group.value,category_id:category.value,package_id:pkg.value});results.innerHTML='<div class="list-group-item text-muted"><span class="spinner-border spinner-border-sm me-2"></span>Searching...</div>';try{const response=await fetch(searchUrl+'?'+params,{headers:{Accept:'application/json'},signal:controller.signal});const data=await response.json();searchExams.clear();data.results.forEach(e=>searchExams.set(Number(e.id),e));matchingTotal=Number(data.total||0);const allFiltered=document.getElementById('cleanup-all-filtered');allFiltered.disabled=matchingTotal===0;allFiltered.innerHTML=`<i class="ri-checkbox-multiple-line me-1"></i>Select all ${matchingTotal} matching paper(s)`;results.innerHTML=data.results.length?data.results.map(e=>`<div class="list-group-item d-flex flex-wrap justify-content-between align-items-center gap-2"><label class="d-flex align-items-center gap-2 mb-0 flex-grow-1"><input class="form-check-input cleanup-paper-check" type="checkbox" data-id="${e.id}" ${selectedPapers.has(Number(e.id))?'checked':''}><span><strong>${escape(e.text)}</strong><span class="small text-muted ms-2">${e.question_count} questions</span></span></label><button type="button" class="btn btn-sm btn-outline-primary cleanup-open-paper" data-id="${e.id}">Choose individual images</button></div>`).join(''):'<div class="list-group-item text-muted">No matching exams with images.</div>';note.textContent=`${matchingTotal} matching paper(s); first 30 shown. Use Select all matching papers to include every result.`;}catch(e){if(e.name!=='AbortError')results.innerHTML='<div class="list-group-item text-danger">Paper search failed.</div>';}};
 const schedule=()=>{clearTimeout(timer);timer=setTimeout(query,250);};
 const renderImages=()=>{const term=filter.value.trim().toLowerCase();grid.innerHTML=images.map(i=>{const text=`${i.question_code} ${i.paper_number} ${i.field_label} ${i.question_text}`.toLowerCase(),show=!term||text.includes(term);return `<div class="col-md-6 col-xl-4 cleanup-image-card ${show?'':'d-none'}"><label class="card h-100 border cleanup-image-label"><div class="card-header d-flex gap-2"><input class="form-check-input cleanup-image-check" type="checkbox" name="selected_images[]" value="${escape(i.token)}"><div><strong>Paper Q. ${i.paper_number} &middot; ${escape(i.field_label)}</strong><div class="small text-muted">${escape(i.question_code)} &middot; image ${i.image_index+1}</div></div></div><div class="card-body"><div class="cleanup-thumb"><img src="${escape(i.src)}" alt="Existing question image" loading="lazy"></div><div class="small mt-2">${escape(i.question_text)}</div></div></label></div>`}).join('');syncImages();document.getElementById('cleanup-image-count').textContent=images.length;};
 const syncImages=()=>{const count=document.querySelectorAll('.cleanup-image-check:checked').length;document.getElementById('cleanup-selected-count').textContent=count;start.disabled=count===0||!examId.value;start.innerHTML=isLocal()?`<i class="ri-contrast-2-line me-1"></i>Process ${count} selected image${count===1?'':'s'} locally (0 API calls)`:`<i class="ri-magic-line me-1"></i>Process ${count} selected image${count===1?'':'s'} only (${count} API call${count===1?'':'s'})`;document.querySelectorAll('.cleanup-image-check').forEach(c=>c.closest('.cleanup-image-label').classList.toggle('border-primary',c.checked));if(count&&examId.value){const id=Number(examId.value);selectedPapers.delete(id);renderPaperSelection();const paperCheck=results.querySelector(`.cleanup-paper-check[data-id="${id}"]`);if(paperCheck)paperCheck.checked=false;}};
 const loadPaper=async(id,name)=>{id=Number(id);examId.value=id;document.getElementById('cleanup-selected-exam').textContent=name;imagePanel.classList.remove('d-none');grid.innerHTML='<div class="col-12 text-center py-5"><span class="spinner-border me-2"></span>Loading existing images...</div>';images=await fetchImages(id);renderImages();};
 [group,category,pkg].forEach(el=>el.addEventListener('change',()=>{if(el===group||el===category)refill();examId.value='';imagePanel.classList.add('d-none');schedule();}));
 search.addEventListener('input',schedule);filter.addEventListener('input',renderImages);grid.addEventListener('change',syncImages);
 action.addEventListener('change',()=>{renderPaperSelection();syncImages();});
 results.addEventListener('change',async e=>{const c=e.target.closest('.cleanup-paper-check');if(!c)return;const id=Number(c.dataset.id),item=searchExams.get(id);if(c.checked&&Number(examId.value)===id){document.querySelectorAll('.cleanup-image-check').forEach(image=>image.checked=false);syncImages();}const accepted=await selectPaper(id,item?.text||'Paper',c.checked);if(!accepted)c.checked=false;});
 results.addEventListener('click',async e=>{const b=e.target.closest('.cleanup-open-paper');if(!b)return;const id=Number(b.dataset.id),item=searchExams.get(id);selectedPapers.delete(id);renderPaperSelection();const checkbox=results.querySelector(`.cleanup-paper-check[data-id="${id}"]`);if(checkbox)checkbox.checked=false;await loadPaper(id,item?.text||'Paper');});
 paperList.addEventListener('click',e=>{const b=e.target.closest('.cleanup-remove-paper');if(!b)return;selectedPapers.delete(Number(b.dataset.id));renderPaperSelection();const checkbox=results.querySelector(`.cleanup-paper-check[data-id="${b.dataset.id}"]`);if(checkbox)checkbox.checked=false;});
 document.getElementById('cleanup-clear-papers').addEventListener('click',()=>{selectedPapers.clear();renderPaperSelection();results.querySelectorAll('.cleanup-paper-check').forEach(c=>c.checked=false);});
 document.getElementById('cleanup-select-visible').addEventListener('click',()=>{document.querySelectorAll('.cleanup-image-card:not(.d-none) .cleanup-image-check').forEach(c=>c.checked=true);syncImages();});
 document.getElementById('cleanup-clear-selection').addEventListener('click',()=>{document.querySelectorAll('.cleanup-image-check').forEach(c=>c.checked=false);syncImages();});
 document.getElementById('cleanup-form').addEventListener('submit',async e=>{if(e.submitter?.value==='all_images'){const total=[...selectedPapers.keys()].reduce((sum,id)=>sum+(imageCache.get(id)?.length||0),0);if(!confirm(isLocal()?`Process ${total} image(s) from ${selectedPapers.size} paper(s) locally with 0 API requests?`:`Process ${total} image(s) from ${selectedPapers.size} paper(s)? This starts ${total} paid image API requests.`))e.preventDefault();return;}if(e.submitter?.value==='all_filtered'&&!allFilteredSubmitting){e.preventDefault();syncFilterInputs();const button=document.getElementById('cleanup-all-filtered'),original=button.innerHTML;button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-1"></span>Counting images...';try{const params=new URLSearchParams({q:search.value,group_id:group.value,category_id:category.value,package_id:pkg.value}),response=await fetch(summaryUrl+'?'+params,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Summary failed');const summary=await response.json();if(Number(summary.image_count)>5000){alert(`This selection contains ${summary.image_count} images. Narrow the filters to 5,000 images or fewer.`);return;}if(confirm(isLocal()?`Process every image in all ${summary.paper_count} matching paper(s) locally? ${summary.image_count} images and 0 API requests.`:`Process every image in all ${summary.paper_count} matching paper(s)? ${summary.image_count} images will create ${summary.image_count} paid API requests.`)){allFilteredSubmitting=true;const mode=document.createElement('input');mode.type='hidden';mode.name='selection_mode';mode.value='all_filtered';e.currentTarget.appendChild(mode);e.currentTarget.submit();}}catch(error){alert('Could not calculate the filtered paper cost. Please try again.');}finally{button.disabled=matchingTotal===0;button.innerHTML=original;}}});
 const runChecks=[...document.querySelectorAll('.cleanup-run-check:not(:disabled)')],runMaster=document.getElementById('cleanup-select-all-runs'),publishSelected=document.getElementById('cleanup-publish-selected-runs'),syncRuns=()=>{const count=runChecks.filter(c=>c.checked).length;publishSelected.disabled=count===0;publishSelected.innerHTML=`<i class="ri-check-double-line me-1"></i>Publish selected${count?' ('+count+')':''}`;runMaster.checked=runChecks.length>0&&count===runChecks.length;runMaster.indeterminate=count>0&&count<runChecks.length;};runChecks.forEach(c=>c.addEventListener('change',syncRuns));runMaster?.addEventListener('change',()=>{runChecks.forEach(c=>c.checked=runMaster.checked);syncRuns();});syncRuns();
 refill();query();
});
</script>
<style>.cleanup-thumb{height:210px;background:#f1f5f9;border-radius:.5rem;display:flex;align-items:center;justify-content:center;overflow:hidden}.cleanup-thumb img{max-width:100%;max-height:100%;object-fit:contain}.cleanup-image-label{cursor:pointer;transition:.15s}.cleanup-image-label:hover{box-shadow:0 5px 16px rgba(15,23,42,.1)}.cleanup-image-label.border-primary{box-shadow:0 0 0 .18rem rgba(13,110,253,.12)}.cleanup-remove-paper{font-size:.65rem}</style>
@endsection
