@extends('layouts.master')
@section('title', 'Review Image Cleanup')
@section('content')
@component('components.breadcrumb') @slot('li_1', 'Image Cleanup Bot') @slot('title', 'Review Drafts') @endcomponent
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card mb-3"><div class="card-body d-flex flex-wrap justify-content-between align-items-start gap-3"><div><a href="{{ route('image-cleanup.index') }}" class="text-muted"><i class="ri-arrow-left-line"></i> Image Cleanup Bot</a><h3 class="mt-2 mb-1">{{ $run->exam?->name }}</h3><div class="text-muted">{{ ucfirst($run->provider) }} &middot; {{ $run->model }} &middot; {{ str_replace('_',' ',ucfirst($run->action)) }}</div></div><div class="d-flex align-items-center gap-2"><span class="badge fs-6 bg-{{ $run->status==='completed'?'success':(in_array($run->status,['failed','cancelled'])?'danger':'warning') }}">{{ ucfirst(str_replace('_',' ',$run->status)) }}</span>@if(in_array($run->status,['queued','starting','running']))<form method="POST" action="{{ route('image-cleanup.stop',$run) }}">@csrf<button class="btn btn-danger"><i class="ri-stop-circle-line me-1"></i>Stop now</button></form>@endif</div></div></div>
@if($run->status==='stop_requested')<div class="alert alert-warning">Stopping after the current image. No new processing will start.</div>@endif
@if($run->failure_message)<div class="alert alert-danger">{{ $run->failure_message }}</div>@endif
<div class="row g-3 mb-3"><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Selected</div><div class="display-6">{{ $run->total_images }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Processed</div><div class="display-6">{{ $run->processed_images }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Ready</div><div class="display-6 text-success">{{ $run->ready_count }}</div></div></div></div><div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Failed</div><div class="display-6 text-danger">{{ $run->failed_count }}</div></div></div></div></div>

@php $canReprocess = in_array($run->status, ['completed', 'failed', 'cancelled'], true) && $run->action !== 'remove_image'; $isLocal = $run->provider === 'local'; @endphp
@if($canReprocess && $reprocessableCount)
<div class="card mb-3 border-primary"><div class="card-header"><h5 class="mb-1"><i class="ri-file-edit-line me-1"></i>Correct all images in this paper</h5><div class="small text-muted">This shared instruction is appended to the standard preservation prompt for every image in this run. Published items restart from the current live image, and saved individual instructions are retained.</div></div><form method="POST" action="{{ route('image-cleanup.reprocess-paper', $run) }}" data-swal-confirm="{{ $isLocal ? 'Reprocess all '.$reprocessableCount.' images locally with 0 API requests?' : 'Reprocess all '.$reprocessableCount.' images? This creates '.$reprocessableCount.' additional paid API requests.' }}">@csrf<div class="card-body"><label class="form-label" for="paper-correction-prompt">Additional paper prompt</label><textarea class="form-control" id="paper-correction-prompt" name="instructions" rows="3" maxlength="2000" required placeholder="Example: Preserve thin arrows and all subscripts exactly; improve only line clarity.">{{ $run->instructions }}</textarea></div><div class="card-footer d-flex flex-wrap justify-content-between align-items-center gap-2"><span class="text-muted small">{{ $isLocal ? $reprocessableCount.' image(s), 0 API requests.' : $reprocessableCount.' image(s) = '.$reprocessableCount.' new paid API request(s).' }}</span><button class="btn btn-primary"><i class="ri-refresh-line me-1"></i>Reprocess complete paper draft</button></div></form></div>
@endif

<form method="POST" id="cleanup-review-form" class="d-none">@csrf</form>
<div class="card"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="mb-1">Original versus generated draft</h5><div class="small text-muted">Verify every label, arrow, number, formula and dimension. Nothing changes live until Publish selected.</div></div><div class="d-flex gap-2"><button class="btn btn-outline-danger cleanup-selection-action" type="submit" form="cleanup-review-form" formaction="{{ route('image-cleanup.reject',$run) }}" disabled>Reject selected</button><button class="btn btn-success cleanup-selection-action" type="submit" form="cleanup-review-form" formaction="{{ route('image-cleanup.publish',$run) }}" data-swal-confirm="Publish the selected generated images? Previous question versions will be saved." disabled><i class="ri-check-double-line me-1"></i>Publish selected</button></div></div><div class="card-body">
@forelse($items as $item)<article class="border rounded p-3 mb-3"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div class="d-flex gap-2">@if($item->status === 'ready')<input class="form-check-input cleanup-item-check" type="checkbox" name="item_ids[]" value="{{ $item->id }}" form="cleanup-review-form" title="Select this ready draft to publish or reject">@else<span class="text-muted" title="This selector is only for ready drafts. Use the correction control below to reprocess the image."><i class="ri-checkbox-blank-circle-line"></i></span>@endif<div><strong>Question {{ $item->question_id }} &middot; {{ $item->field==='question'?'Question':($item->field==='explanation'?'Explanation':'Option '.chr(64+(int)substr($item->field,6))) }}</strong><div class="small text-muted">{{ $item->question?->question_code }} &middot; image {{ $item->image_index+1 }}</div></div></div><span class="badge bg-{{ $item->status==='ready'?'success':($item->status==='failed'?'danger':($item->status==='published'?'primary':'secondary')) }}">{{ ucfirst($item->status) }}</span></div>
<div class="row g-3"><div class="col-lg-6"><div class="fw-semibold mb-2">Original</div><div class="cleanup-compare"><img src="{{ $item->original_src }}" alt="Original image"></div></div><div class="col-lg-6"><div class="fw-semibold mb-2">{{ $run->action === 'remove_image' ? 'Removal draft' : 'Generated draft' }}</div><div class="cleanup-compare">@if($run->action === 'remove_image' && $item->status === 'ready')<div class="text-center text-muted"><i class="ri-delete-bin-line fs-1 d-block mb-2"></i>This selected image will be removed when published.</div>@elseif($item->output_path)<img src="{{ Storage::disk('public')->url($item->output_path) }}" alt="Generated image">@elseif(in_array($item->status,['queued','processing']))<div class="text-muted"><span class="spinner-border spinner-border-sm me-2"></span>{{ ucfirst($item->status) }}</div>@else<div class="text-danger">{{ $item->failure_message ?: 'No generated image.' }}</div>@endif</div></div></div>
@if($item->failure_message)<div class="alert alert-danger py-2 mt-3 mb-0">{{ $item->failure_message }}</div>@endif
@if($canReprocess)<form method="POST" action="{{ route('image-cleanup.items.reprocess', [$run, $item]) }}" class="border rounded bg-light p-3 mt-3" data-swal-confirm="{{ $isLocal ? 'Reprocess only this image locally with 0 API requests?' : 'Reprocess only this image? This creates one additional paid API request.' }}">@csrf<label class="form-label fw-semibold" for="item-instructions-{{ $item->id }}"><i class="ri-magic-line me-1"></i>Correct only this image</label><div class="small text-muted mb-2">Describe the minor defect precisely. This instruction affects only this image. If it was already published, processing restarts from the current live image.</div><div class="input-group"><input class="form-control" id="item-instructions-{{ $item->id }}" name="instructions" maxlength="2000" minlength="3" required value="{{ $item->instructions }}" placeholder="Example: Restore the missing arrowhead; keep every label and dimension unchanged."><button class="btn btn-primary"><i class="ri-refresh-line me-1"></i>{{ $isLocal ? 'Reprocess only this image (0 API calls)' : 'Reprocess only this image (1 API call)' }}</button></div></form>@endif</article>
@empty<div class="text-center text-muted py-5">No image items in this run.</div>@endforelse
</div><div class="card-footer">{{ $items->links() }}</div></div>
@if($run->failed_count || $run->status==='cancelled')<form method="POST" action="{{ route('image-cleanup.retry',$run) }}" class="mt-3 text-end">@csrf<button class="btn btn-outline-primary"><i class="ri-refresh-line me-1"></i>Retry failed / cancelled images</button></form>@endif
@endsection
@section('script')<script>document.addEventListener('DOMContentLoaded',()=>{const checks=[...document.querySelectorAll('.cleanup-item-check')],sync=()=>document.querySelectorAll('.cleanup-selection-action').forEach(b=>b.disabled=!checks.some(c=>c.checked));checks.forEach(c=>c.addEventListener('change',sync));});@if(in_array($run->status,['queued','starting','running','stop_requested']))setTimeout(()=>location.reload(),8000);@endif</script><style>.cleanup-compare{min-height:260px;max-height:520px;background:#f1f5f9;border:1px solid #dbe4ea;border-radius:.6rem;display:flex;align-items:center;justify-content:center;overflow:auto}.cleanup-compare img{max-width:100%;max-height:500px;object-fit:contain}</style>@endsection
