@extends('layouts.master')
@section('title', $source->name)
@section('content')
<div class="container-fluid">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a href="{{ route('official-exam-sources.index') }}" class="text-muted"><i class="ri-arrow-left-line me-1"></i>Official Exam Monitor</a><h3 class="mt-2 mb-1">{{ $source->name }}</h3><p class="text-muted mb-0">{{ $source->website_name }} · {{ strtoupper($source->driver) }} · profile v{{ $source->config_version }}</p></div><div class="d-flex gap-2"><form method="POST" action="{{ route('official-exam-sources.run', $source) }}">@csrf<button class="btn btn-primary">Check now</button></form><a class="btn btn-outline-secondary" href="{{ route('official-exam-sources.edit', $source) }}">Edit profile</a></div></div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
    <div class="row g-3 mb-4">
        <div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Status</div><div class="fs-5 fw-semibold">{{ $source->enabled ? 'Monitoring' : 'Disabled' }}</div></div></div></div>
        <div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Schedule</div><div class="fs-5 fw-semibold">Every {{ $source->check_interval_minutes }} min</div><small>Next {{ $source->next_check_at?->diffForHumans() ?? 'now' }}</small></div></div></div>
        <div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Automation</div><div class="fs-5 fw-semibold">{{ $source->automation_mode === 'queue' ? 'Extract automatically' : 'Draft only' }}</div></div></div></div>
        <div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">Source</div><a href="{{ $source->source_url }}" target="_blank" rel="noopener" class="text-break">Open official page</a></div></div></div>
    </div>
    @if($source->last_error)<div class="alert alert-warning"><strong>Latest warning:</strong> {{ $source->last_error }}</div>@endif
    @include('exams.partials.pdf-publication')
    <div class="card mb-4"><div class="card-header"><h5 class="mb-0">Discoveries</h5></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Exam</th><th>Status</th><th>Rule/version</th><th>First seen</th><th>Last seen</th><th>Result</th></tr></thead><tbody>
        @forelse($discoveries as $item)<tr><td>@if($item->exam_id && user_can_route_action('exams.edit', 'edit'))<input type="checkbox" class="form-check-input me-2" form="pdf-publication" name="exam_ids[]" value="{{ $item->exam_id }}" aria-label="Select {{ $item->exam_name }}">@endif<div class="fw-semibold">{{ $item->exam_name }}</div>@if($item->failure_message)<small class="text-danger">{{ $item->failure_message }}</small>@endif</td><td><span class="badge {{ in_array($item->status,['created']) ? 'bg-success-subtle text-success' : (in_array($item->status,['revised','failed']) ? 'bg-danger-subtle text-danger' : 'bg-warning-subtle text-warning') }}">{{ str_replace('_',' ',$item->status) }}</span></td><td>{{ $item->rule?->name ?? 'Unmatched' }}@if($item->rule_version)<small class="text-muted"> v{{ $item->rule_version }}</small>@endif</td><td>{{ $item->first_seen_at?->format('d M Y H:i') }}</td><td>{{ $item->last_seen_at?->diffForHumans() }}</td><td>@if($item->exam)<a href="{{ route('exams.edit', $item->exam) }}">{{ $item->exam->name }}</a><span class="badge bg-light text-dark">{{ $item->exam->status }}</span>@endif @if($item->sourceImport)<a class="d-block small" href="{{ route('source-exams.show', $item->sourceImport) }}">Import: {{ $item->sourceImport->status }}</a>@endif</td></tr>
        @empty<tr><td colspan="6" class="text-center text-muted py-4">No documents have been discovered yet.</td></tr>@endforelse
    </tbody></table></div></div><div class="mb-4">{{ $discoveries->links() }}</div>
    <div class="card"><div class="card-header"><h5 class="mb-0">Recent checks</h5></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Started</th><th>Status</th><th>Found</th><th>Created</th><th>Skipped</th><th>Attention</th></tr></thead><tbody>@forelse($runs as $run)<tr><td>{{ $run->started_at?->format('d M Y H:i') }}</td><td>{{ str_replace('_',' ',$run->status) }}</td><td>{{ $run->found_count }}</td><td>{{ $run->created_count }}</td><td>{{ $run->skipped_count }}</td><td>{{ $run->review_count }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">No checks yet.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
