@extends('layouts.master')
@section('title','Navigation Manager')
@section('content')
@component('components.breadcrumb') @slot('li_1','Website') @slot('title','Navigation Manager') @endcomponent
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="alert alert-info d-flex justify-content-between align-items-center gap-3"><span><strong>Draft workspace:</strong> Load the demo at any time to add missing examples without deleting your items. Arrange everything, then activate Header, Secondary, or Footer.</span><form method="POST" action="{{ route('navigation.defaults') }}">@csrf<button class="btn el-btn-primary text-nowrap">Load Demo Menu</button></form></div><div class="alert alert-light border"><strong>Mega Menu:</strong> The demo &quot;Explore Exams&quot; item is the dynamic Mega Menu. Edit its display text, icon, order and visibility here. Use Edit on that row for its title, icon, order and visibility. Its content is dynamic: Groups form the left column, linked {{ ($subcategoriesEnabled ?? true) ? 'Categories/Subcategories' : 'Categories' }} form the centre, and linked Packages form Featured Packages. Change those records and their display orders in their respective admin sections.</div>

<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Footer Headings</h5><small class="text-muted">Edit the four visible footer headings together.</small></div><div class="card-body"><form method="POST" action="{{ route('navigation.footer-headings') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label">Brand heading</label><input name="footer_brand_label" class="form-control" value="{{ $settings->footer_brand_label }}" placeholder="Examways"></div>@foreach($footerSections as $section)<div class="col-md-3"><label class="form-label">Footer column {{ $loop->iteration }}</label><input type="hidden" name="sections[{{ $loop->index }}][old]" value="{{ $section }}"><input name="sections[{{ $loop->index }}][new]" class="form-control" value="{{ $section }}" required></div>@endforeach</div><button class="btn el-btn-primary mt-3">Save Footer Headings</button></form></div></div>
<div class="row g-4">
 <div class="col-xl-4">
  <div class="card"><div class="card-header"><h5 class="mb-0">Add Menu Item</h5></div><div class="card-body">
   <form method="POST" action="{{ route('navigation.store') }}">@csrf
    <div class="mb-3"><label class="form-label">Location</label><select name="location" class="form-select"><option value="header">Header</option><option value="secondary">Secondary Menu (below header)</option><option value="footer">Footer</option></select></div>
    <div class="mb-3"><label class="form-label">Display Text <span class="text-muted">(optional)</span></label><input name="label" class="form-control" placeholder="Leave blank to use selected destination name"><div class="form-text">Leave blank to automatically show the selected destination name.</div></div>
    <div class="mb-3"><label class="form-label">Destination</label><select name="destination" class="form-select js-destination-search" required>@foreach($destinations as $d)<option value="{{ $d['value'] }}">{{ $d['label'] }}</option>@endforeach</select></div>
    <div class="mb-3"><label class="form-label">Custom URL</label><input name="custom_url" class="form-control" placeholder="https:// or /path"><div class="form-text">Used only when Destination is Custom URL—for an external site, an internal /path not listed above, email (mailto:) or phone (tel:).</div></div>
    <div class="mb-3"><label class="form-label">Footer Column Heading</label><input name="section_label" class="form-control" placeholder="e.g. Explore"></div>
    <div class="mb-3"><label class="form-label">Parent Header Item</label><select name="parent_id" class="form-select"><option value="">No parent</option>@foreach($items->where('location','header')->whereNull('parent_id') as $parent)<option value="{{ $parent->id }}">{{ $parent->label }}</option>@endforeach</select></div>
    <div class="row g-2"><div class="col-6"><label class="form-label">Icon</label><select name="icon" class="form-select">@foreach($icons as $value=>$name)<option value="{{ $value }}">{{ $name }}</option>@endforeach</select></div><div class="col-6"><label class="form-label">Order</label><input type="number" name="sort_order" class="form-control" value="0" min="0"></div></div>
    <div class="row g-2 mt-2"><div class="col-6"><label class="form-label">Open</label><select name="target" class="form-select"><option value="_self">Same tab</option><option value="_blank">New tab</option></select></div><div class="col-6"><label class="form-label">Style</label><select name="style" class="form-select"><option value="link">Link</option><option value="button">Button</option></select></div></div>
    <div class="d-flex flex-wrap gap-3 my-3"><label><input type="checkbox" name="desktop_visible" value="1" checked> Desktop</label><label><input type="checkbox" name="mobile_visible" value="1" checked> Mobile</label><label><input type="checkbox" name="is_active" value="1" checked> Active</label></div>
    <button class="btn el-btn-primary w-100">Add Item</button>
   </form>
  </div></div>
 </div>
 <div class="col-xl-8">
  @foreach(['header'=>'Header Menu','secondary'=>'Secondary Menu','footer'=>'Footer Menu'] as $location=>$heading)
   <div class="card mb-4"><div class="card-header d-flex justify-content-between align-items-center"><div><h5 class="mb-0">{{ $heading }}</h5><small class="text-muted">Drag vertically to reorder. Header supports submenus; Secondary is the slim featured-links row below the header; Footer is grouped by column heading.</small></div><form method="POST" action="{{ route('navigation.toggle') }}">@csrf<input type="hidden" name="location" value="{{ $location }}"><button class="btn btn-sm {{ $settings->{$location.'_enabled'} ? 'btn-outline-danger' : 'el-btn-primary' }}">{{ $settings->{$location.'_enabled'} ? 'Deactivate custom menu' : 'Activate custom menu' }}</button><div class="small mt-1 {{ $settings->{$location.'_enabled'} ? 'text-success' : 'text-muted' }}">{{ $settings->{$location.'_enabled'} ? 'Custom menu is live' : ($location === 'secondary' ? 'Secondary menu is hidden' : 'Default menu is live') }}</div></form></div>
    <div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><tbody class="js-sortable" data-location="{{ $location }}">
     @forelse($items->where('location',$location) as $item)
      <tr draggable="true" data-id="{{ $item->id }}" data-parent="{{ $item->parent_id }}"><td style="width:42px;cursor:grab"><i class="ri-drag-move-2-line fs-4"></i></td><td class="nav-item-label" style="padding-left:{{ $item->parent_id ? '42px' : '12px' }}"><span class="nav-indent text-muted me-2 {{ $item->parent_id ? '' : 'd-none' }}">&rdsh;</span><strong>{{ $item->label }}</strong>@if($item->link_type === 'mega_exams') <span class="badge bg-warning text-dark ms-2">MEGA MENU</span>@endif<div class="small text-muted">{{ $item->link_type }} @if($item->section_label) &middot; {{ $item->section_label }} @endif</div></td><td><span class="badge {{ $item->is_active?'bg-success':'bg-secondary' }}">{{ $item->is_active?'Active':'Hidden' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary js-edit" data-item="{{ json_encode($item->only(['id','location','label','link_type','reference_id','custom_url','section_label','parent_id','icon','target','style','desktop_visible','mobile_visible','is_active','sort_order'])) }}">Edit</button> <form class="d-inline" method="POST" action="{{ route('navigation.destroy',$item) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" data-swal-confirm="Remove this menu item?">Remove</button></form></td></tr>
     @empty<tr><td class="text-center text-muted py-4">Using safe default navigation. Add an item to take control.</td></tr>@endforelse
    </tbody></table></div></div>
   </div>
  @endforeach
 </div>
</div>

<div class="modal fade" id="editNavigationModal"><div class="modal-dialog"><div class="modal-content"><form method="POST" id="editNavigationForm">@csrf @method('PUT')<div class="modal-header"><h5>Edit Menu Item</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="location" id="edit-location"><div class="mb-3"><label>Display Text <span class="text-muted">(optional)</span></label><input name="label" id="edit-label" class="form-control" placeholder="Use destination name automatically"></div><div class="mb-3"><label>Destination</label><select name="destination" id="edit-destination" class="form-select js-destination-search">@foreach($destinations as $d)<option value="{{ $d['value'] }}">{{ $d['label'] }}</option>@endforeach</select></div><div class="mb-3"><label>Custom URL</label><input name="custom_url" id="edit-custom_url" class="form-control"><div class="form-text">Only used when Destination is Custom URL.</div></div><div class="mb-3"><label>Footer Column Heading</label><input name="section_label" id="edit-section_label" class="form-control"></div><div class="mb-3"><label>Parent Header Item</label><select name="parent_id" id="edit-parent_id" class="form-select"><option value="">No parent</option>@foreach($items->where('location','header')->whereNull('parent_id') as $parent)<option value="{{ $parent->id }}">{{ $parent->label }}</option>@endforeach</select></div><div class="row g-2 mb-3"><div class="col-6"><label>Icon</label><select name="icon" id="edit-icon" class="form-select">@foreach($icons as $value=>$name)<option value="{{ $value }}">{{ $name }}</option>@endforeach</select></div><div class="col-6"><label>Order</label><input type="number" name="sort_order" id="edit-sort_order" class="form-control" min="0"></div></div><div class="row g-2 mb-3"><div class="col-6"><label>Open</label><select name="target" id="edit-target" class="form-select"><option value="_self">Same tab</option><option value="_blank">New tab</option></select></div><div class="col-6"><label>Style</label><select name="style" id="edit-style" class="form-select"><option value="link">Link</option><option value="button">Button</option></select></div></div><label><input type="checkbox" name="desktop_visible" value="1" id="edit-desktop_visible"> Desktop</label> <label><input type="checkbox" name="mobile_visible" value="1" id="edit-mobile_visible"> Mobile</label> <label><input type="checkbox" name="is_active" value="1" id="edit-is_active"> Active</label></div><div class="modal-footer"><button class="btn el-btn-primary">Update</button></div></form></div></div></div>
@endsection
@section('script')<script>
$('.js-destination-search').not('#edit-destination').select2({width:'100%',placeholder:'Type to search destinations'});
$('#edit-destination').select2({width:'100%',dropdownParent:$('#editNavigationModal'),placeholder:'Type to search destinations'});
document.querySelectorAll('.js-edit').forEach(b=>b.onclick=()=>{const x=JSON.parse(b.dataset.item);const f=document.getElementById('editNavigationForm');f.action='{{ url('navigation') }}/'+x.id;['location','label','custom_url','section_label','parent_id','icon','target','style','sort_order'].forEach(k=>document.getElementById('edit-'+k).value=x[k]??'');document.getElementById('edit-destination').value=x.link_type+':'+(x.reference_id??'');$('#edit-destination').trigger('change.select2');['desktop_visible','mobile_visible','is_active'].forEach(k=>document.getElementById('edit-'+k).checked=!!x[k]);bootstrap.Modal.getOrCreateInstance(document.getElementById('editNavigationModal')).show()});
document.querySelectorAll('.js-sortable').forEach(list=>{
 let row=null,nest=false;
 const paint=(target,isChild)=>{list.querySelectorAll('tr').forEach(x=>x.classList.remove('table-info'));if(target&&isChild)target.classList.add('table-info')};
 const save=()=>fetch('{{ route('navigation.reorder') }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({location:list.dataset.location,items:[...list.querySelectorAll('tr[data-id]')].map(x=>({id:x.dataset.id,parent_id:x.dataset.parent||null}))})});
 list.addEventListener('dragstart',e=>{row=e.target.closest('tr');row?.classList.add('opacity-50')});
 list.addEventListener('dragend',()=>{row?.classList.remove('opacity-50');paint();row=null});
 list.addEventListener('dragover',e=>{e.preventDefault();const over=e.target.closest('tr[data-id]');if(!row||!over||row===over)return;nest=list.dataset.location==='header'&&e.clientX>over.getBoundingClientRect().left+180;paint(over,nest);if(!nest)list.insertBefore(row,over)});
 list.addEventListener('drop',e=>{e.preventDefault();const over=e.target.closest('tr[data-id]');if(!row||!over||row===over)return;let parent=null;if(nest){parent=over.dataset.parent||over.dataset.id;row.dataset.parent=parent;over.after(row)}else{row.dataset.parent=''}const label=row.querySelector('.nav-item-label'),indent=row.querySelector('.nav-indent');label.style.paddingLeft=parent?'42px':'12px';indent.classList.toggle('d-none',!parent);paint();save().then(r=>{if(!r.ok)location.reload()})});
});
</script>@endsection

