<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QA Preview</title>
<script>window.MathJax={loader:{load:['[tex]/mhchem']},tex:{packages:{'[+]':['mhchem']},inlineMath:[['\\(','\\)'],['$','$']],displayMath:[['\\[','\\]'],['$$','$$']],processEscapes:true},svg:{fontCache:'global'}};</script><script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
<style>body{margin:0;background:#f3f7f6;color:#142033;font-family:Arial,sans-serif}.shell{max-width:980px;margin:40px auto;padding:28px;background:#fff;border:1px solid #d7e2df;border-radius:12px}.meta{color:#64748b;font-size:14px;margin-bottom:20px}.body{font-size:20px;line-height:1.65;overflow-wrap:anywhere}.option{display:flex;gap:12px;border:1px solid #d7e2df;border-radius:8px;padding:13px 16px;margin-top:12px}.key{font-weight:700;color:#0f766e}.answer{margin-top:20px;padding:14px;background:#eef7f5;border-radius:8px}img{max-width:100%;height:auto}mjx-container{max-width:100%;overflow-x:auto;overflow-y:hidden}</style></head><body><main class="shell"><div class="meta">Automated QA preview · Question {{ $question->id }} · {{ $question->qtype?->question_type }}</div><div class="body" data-qa-question-body>{!! $question->question !!}</div>
@if(str_starts_with($questionType,'multiple_choice')) @foreach(range(1,6) as $i) @if(trim(strip_tags((string)$question->{'option'.$i}))!=='')<div class="option" data-qa-option><span class="key">{{ chr(64+$i) }}.</span><span>{!! $question->{'option'.$i} !!}</span></div>@endif @endforeach
@elseif($questionType==='true_false')<div class="option" data-qa-option>True</div><div class="option" data-qa-option>False</div>
@elseif($questionType==='fill_blank')<div class="answer">@for($i=1;$i<=$fillBlankCount;$i)<input aria-label="Blank {{ $i }}" placeholder="Type answer {{ $i }}" style="padding:10px;margin:5px;border:1px solid #94a3b8;border-radius:6px">@endfor</div>
@elseif($questionType==='nat')<div class="answer"><input type="number" step="any" placeholder="Enter numerical answer" style="padding:10px;border:1px solid #94a3b8;border-radius:6px"></div>
@else<div class="answer"><textarea rows="5" style="width:100%" placeholder="Write your answer"></textarea></div>@endif
</main></body></html>
