@extends('layouts.master')
@section('title','Repair Release')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-3"><div><a href="{{ route('exam-quality.show',$release->audit_id) }}" class="text-muted"><i class="ri-arrow-left-line"></i> Back to audit</a><h3 class="mt-2 mb-1">{{ $release->name }}</h3><div class="text-muted">{{ $release->exam?->name }} &middot; published {{ optional($release->published_at)->format('d M Y, h:i A') }} by {{ $release->creator?->name ?: 'System' }}</div></div><span class="badge rounded-pill px-3 py-2 bg-{{ $release->status==='published'?'success':'warning' }} align-self-start" style="font-size:.85rem;line-height:1"><i class="ri-checkbox-circle-line me-1"></i>{{ ucfirst(str_replace('_',' ',$release->status)) }}</span></div>
<div class="alert alert-warning"><strong>Rollback:</strong> Restore returns selected questions to their exact versions from before this release. The current content is saved first, so the rollback can also be reversed later.</div>
<form method="POST" action="{{ route('exam-quality.releases.restore',$release) }}" id="release-restore-form">@csrf @method('PATCH')
<div class="card"><div class="card-header d-flex flex-wrap justify-content-between gap-2"><div><h4 class="mb-1">Release questions</h4><div class="text-muted">{{ $release->items->where('status','published')->count() }} currently published &middot; {{ $release->items->where('status','restored')->count() }} restored</div></div><div class="d-flex gap-2"><button class="btn btn-warning" id="restore-selected" disabled data-swal-confirm="Restore the selected questions to their pre-release versions?"><i class="ri-history-line me-1"></i>Restore selected</button><button class="btn btn-outline-warning" name="restore_all" value="1" data-swal-confirm="Restore every currently published question in this release?"><i class="ri-restart-line me-1"></i>Restore entire release</button></div></div>
<div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th style="width:50px"><input class="form-check-input" type="checkbox" id="select-release-items" aria-label="Select all currently published questions" title="Select all currently published questions"></th><th>Question</th><th>Changed fields</th><th>Status</th><th></th></tr></thead><tbody>
@foreach($release->items as $item)<tr><td>@if($item->status==='published')<input class="form-check-input release-item-checkbox" type="checkbox" name="item_ids[]" value="{{ $item->id }}">@endif</td><td><strong>ID {{ $item->question_id }}</strong><div class="small text-muted">{{ $item->question?->question_code }}</div><div class="text-truncate" style="max-width:520px">{{ strip_tags((string)$item->question?->question) }}</div></td><td>@foreach((array)$item->repairDraft?->changed_fields as $field)<span class="badge bg-light text-dark me-1 mb-1">{{ str_replace('_',' ',$field) }}</span>@endforeach</td><td><span class="badge bg-{{ $item->status==='published'?'success':'warning' }}">{{ ucfirst($item->status) }}</span></td><td class="text-end"><a href="{{ route('exam-quality.repairs.show',$item->repair_draft_id) }}" class="btn btn-sm btn-outline-primary">View draft</a></td></tr>@endforeach
</tbody></table></div></div></div></form>
<script>document.addEventListener('DOMContentLoaded',()=>{const boxes=[...document.querySelectorAll('.release-item-checkbox')],button=document.getElementById('restore-selected'),all=document.getElementById('select-release-items');const sync=()=>{const selected=boxes.filter(x=>x.checked).length;button.disabled=selected===0;button.innerHTML=`<i class="ri-history-line me-1"></i>Restore selected${selected?` (${selected})`:''}`;all.checked=boxes.length>0&&selected===boxes.length;all.indeterminate=selected>0&&selected<boxes.length;all.disabled=boxes.length===0;};boxes.forEach(x=>x.addEventListener('change',sync));all?.addEventListener('change',()=>{boxes.forEach(x=>x.checked=all.checked);sync();});sync();});</script>
@endsection
