<?php
// Direct PDF Generator for ExamElite
// Access: http://94.136.186.150/exam_pdf.php?exam_id=1

error_reporting(E_ALL);
ini_set("display_errors", 1);

$exam_id = isset($_GET["exam_id"]) ? intval($_GET["exam_id"]) : 0;

if ($exam_id == 0) {
    die("Please provide exam_id parameter (e.g., ?exam_id=1)");
}

// Database connection
$host = "localhost";
$dbname = "examelite";
$user = "examelite";
$pass = "FATIMA@hasan7";

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Get exam details
    $stmt = $pdo->prepare("SELECT id, name, duration FROM exams WHERE id = ?");
    $stmt->execute([$exam_id]);
    $exam = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$exam) {
        die("Exam not found with ID: $exam_id");
    }
    
    // Get questions for this exam
    $stmt = $pdo->prepare("
        SELECT q.* 
        FROM questions q
        INNER JOIN exam_questions eq ON q.id = eq.question_id
        WHERE eq.exam_id = ?
        ORDER BY eq.id
    ");
    $stmt->execute([$exam_id]);
    $questions = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    if (empty($questions)) {
        die("No questions found for exam ID: $exam_id");
    }
    
    // Output as HTML for now (for testing)
    header("Content-Type: text/html");
    
    echo "<!DOCTYPE html>";
    echo "<html>";
    echo "<head><meta charset=\"UTF-8\"><title>" . htmlspecialchars($exam["name"]) . "</title>";
    echo "<style>";
    echo "body { font-family: Arial, sans-serif; margin: 20px; }";
    echo ".header { text-align: center; margin-bottom: 30px; }";
    echo ".question { margin-bottom: 30px; border-left: 3px solid #0d9488; padding-left: 15px; }";
    echo ".options { margin-left: 20px; margin-top: 10px; }";
    echo ".option { margin: 5px 0; }";
    echo "</style></head>";
    echo "<body>";
    echo "<div class=\"header\">";
    echo "<h1>" . htmlspecialchars($exam["name"]) . "</h1>";
    echo "<p>Total Questions: " . count($questions) . " | Duration: " . ($exam["duration"] ?? "N/A") . " minutes</p>";
    echo "<hr>";
    echo "</div>";
    
    $counter = 1;
    foreach ($questions as $q) {
        echo "<div class=\"question\">";
        echo "<strong>Question " . $counter . ":</strong> " . nl2br(htmlspecialchars($q["question"])) . "<br>";
        echo "<div class=\"options\">";
        if (!empty($q["option1"])) echo "<div class=\"option\"><strong>A.</strong> " . nl2br(htmlspecialchars($q["option1"])) . "</div>";
        if (!empty($q["option2"])) echo "<div class=\"option\"><strong>B.</strong> " . nl2br(htmlspecialchars($q["option2"])) . "</div>";
        if (!empty($q["option3"])) echo "<div class=\"option\"><strong>C.</strong> " . nl2br(htmlspecialchars($q["option3"])) . "</div>";
        if (!empty($q["option4"])) echo "<div class=\"option\"><strong>D.</strong> " . nl2br(htmlspecialchars($q["option4"])) . "</div>";
        echo "</div>";
        echo "</div>";
        $counter++;
    }
    
    echo "<hr><footer style=\"text-align: center; font-size: 12px; color: #666;\">Generated by ExamElite | " . date("Y-m-d H:i:s") . "</footer>";
    echo "</body></html>";
    
} catch(PDOException $e) {
    echo "Database Error: " . $e->getMessage();
} catch(Exception $e) {
    echo "Error: " . $e->getMessage();
}
?>
