<?php
require __DIR__.'/test-central-exam-authoring.php';
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\{Exam,Question};
$centralSubject=$service->saveCentralTaxonomy(10,$centralActor,'subjects',0,['subject_name'=>'Central paper subject','group_ids'=>[$centralGroup->id]],'new',$uuid());
$centralSection=$service->saveCentralTaxonomy(10,$centralActor,'sections',0,['name'=>'Central question section','group_ids'=>[$centralGroup->id],'status'=>true],'new',$uuid());
$centralQuestion=$q->replicate();$centralQuestion->organization_id=10;$centralQuestion->subject_id=$centralSubject['id'];$centralQuestion->language_id=$centralLanguage->id;$centralQuestion->save();$centralQuestion->groups()->sync([$centralGroup->id]);
$action=function($name,$fields,$revision,$key)use($centralController,$centralActor,$centralExam){
 $result=$centralController->centralExamAction(Request::create('/','POST',['actor_id'=>$centralActor,'fields'=>$fields,'revision'=>$revision,'request_id'=>$key]),(string)$centralExam['id'],$name);
 if($result['conflict']??false)abort(409);
 if(!$result['saved'])throw Illuminate\Validation\ValidationException::withMessages($result['errors']);
 return $result['record'];
};
$snapshot=fn()=>$service->record('exams',Exam::findOrFail($centralExam['id']));
$current=$snapshot();$before=$current;$key=$uuid();$add=['question_ids'=>[$centralQuestion->id]];
$current=$action('add-questions',$add,$current['revision'],$key);
check(Exam::find($centralExam['id'])->questions()->whereKey($centralQuestion->id)->exists(),'Central paper adds an owned question');
check($action('add-questions',$add,$before['revision'],$key)===$current,'Central paper add replay');
$listed=$controller->centralExamQuestions(Request::create('/','GET'),(string)$centralExam['id']);
check(array_column($listed['items'],'id')===[$centralQuestion->id]&&$listed['next']===null,'Central attached questions read is scoped');
$deny(fn()=>$controller->centralExamQuestions(Request::create('/','GET'),(string)$exam['id']));
$deny(fn()=>$controller->centralExamQuestions(Request::create('/','GET',['owner'=>20]),(string)$centralExam['id']));
$deny(fn()=>$controller->centralExamQuestions(Request::create('/','GET',['after'=>'-1']),(string)$centralExam['id']));

$deny(fn()=>$action('add-questions',['question_ids'=>[$q->id]],$current['revision'],$uuid()));
$deny(fn()=>$action('remove-questions',['question_ids'=>[$q->id]],$current['revision'],$uuid()));
$deny(fn()=>$action('add-questions',$add,$before['revision'],$uuid()));
$current=$action('set-status',['status'=>'Active'],$current['revision'],$uuid());check($current['status']==='Active','Central exam activation');
$before=$current;$key=$uuid();$current=$action('set-result-status',['result_after_finish'=>false],$current['revision'],$key);
check(!$current['fields']['result_after_finish']&&$action('set-result-status',['result_after_finish'=>false],$before['revision'],$key)===$current,'Central result visibility uses desired state and stable retries');
$current=$action('create-section',['name'=>'Central part A','display_order'=>1,'duration'=>20],$current['revision'],$uuid());$centralPaperSection=$current['sections'][0]['id'];
$deny(fn()=>$action('create-section',['name'=>'Too long','duration'=>100],$current['revision'],$uuid()));
$deny(fn()=>$action('update-section',['section_id'=>1,'name'=>'Foreign'],$current['revision'],$uuid()));
$current=$action('update-section',['section_id'=>$centralPaperSection,'name'=>'Central part A revised','duration'=>15],$current['revision'],$uuid());
check($current['sections'][0]['name']==='Central part A revised','Central paper section edit');
$current=$action('assign-section',['question_ids'=>[$centralQuestion->id],'question_section_id'=>$centralSection['id']],$current['revision'],$uuid());
check(DB::table('exam_questions')->where('exam_id',$centralExam['id'])->where('question_id',$centralQuestion->id)->value('exam_section_id')!==null,'Central question assigned to owned section definition');
$deny(fn()=>$action('assign-section',['question_ids'=>[$centralQuestion->id],'question_section_id'=>$section['id']],$current['revision'],$uuid()));
$deny(fn()=>$action('subject-timers',['subject_ids'=>[$subject['id']],'durations'=>[10]],$current['revision'],$uuid()));
$current=$action('subject-timers',['subject_ids'=>[$centralSubject['id']],'durations'=>[30]],$current['revision'],$uuid());
check((int)$current['subject_durations'][0]['duration']===30,'Central subject duration is stored by native controller');
$deny(fn()=>$action('subject-timers',['subject_ids'=>[$centralSubject['id']],'durations'=>[100]],$current['revision'],$uuid()));
$current=$action('remove-section',['section_id'=>$centralPaperSection],$current['revision'],$uuid());
check(!App\Models\ExamSection::find($centralPaperSection),'Central empty section removal');
$current=$action('remove-questions',$add,$current['revision'],$uuid());
check(!Exam::find($centralExam['id'])->questions()->whereKey($centralQuestion->id)->exists(),'Central question removal');
foreach(['generate-document','refresh-translation','unknown','set-image'] as $unsupported)$deny(fn()=>$action($unsupported,['name'=>'invalid'],$current['revision'],$uuid()));
$deny(fn()=>$action('set-status',['status'=>'Active','organization_id'=>20],$current['revision'],$uuid()));
check($service->record('exams',Exam::findOrFail($exam['id']))===$orgExamBefore,'Central paper actions preserve organisation exam');
echo "Central native paper controls: questions, sections, timers, status, scope and retries passed.\n";
