<?php
require __DIR__.'/test-native-plan-editor.php';
use App\Models\SaasPlan;
use Illuminate\Support\Facades\DB;
$created=$editor->createForActor(10,$centralActor,$nextId(),['name'=>'Plan to edit','feature_reports'=>false,'limit_students'=>12]);
$planId=$created['plan_id'];$plan=SaasPlan::findOrFail($planId);$slug=$plan->slug;
DB::table('organizations')->where('id',20)->update(['saas_plan_id'=>$planId]);
$orgBefore=DB::table('organizations')->orderBy('id')->get()->toJson();
$read=fn()=>$planController->centralPlan(Illuminate\Http\Request::create('/','GET'),(string)$planId);
$snapshot=$read();
check($snapshot['assigned_organisations']===1&&$snapshot['fields']['limit_students']===12&&!$snapshot['fields']['feature_reports'],'Private plan detail includes reviewed settings and assignment count');
$payload=['actor_id'=>$centralActor,'request_id'=>$nextId(),'revision'=>$snapshot['revision'],'fields'=>['name'=>'Renamed plan','feature_reports'=>true,'status'=>false]];
$call=fn($body)=>$planController->updatePlan(Illuminate\Http\Request::create('/','POST',$body),(string)$planId);
$updated=$call($payload);$audits=count($GLOBALS['planAudit']);
check($updated['saved']&&$updated['revision']!==$snapshot['revision'],'Native plan edit changes revision');
check($call($payload)===$updated&&count($GLOBALS['planAudit'])===$audits,'Plan update receipt prevents repeat native write');
$after=$read();
check($after['fields']['feature_reports']===true&&$after['fields']['status']===false&&$after['fields']['limit_students']===12&&$after['fields']['feature_ai_translation']===true,'Partial native edit preserves omitted limits and permissions');
check(SaasPlan::findOrFail($planId)->slug===$slug&&DB::table('organizations')->orderBy('id')->get()->toJson()===$orgBefore,'Plan edit preserves slug, organisation details and assignment IDs');
check($call(array_replace($payload,['request_id'=>$nextId()]))===['saved'=>false,'conflict'=>true],'Stale edit rejected');
check($call(array_replace($payload,['fields'=>['name'=>'Changed retry']]))===['saved'=>false,'conflict'=>true],'Changed payload cannot replay edit');
$valid=array_replace($payload,['request_id'=>$nextId(),'revision'=>$after['revision']]);
foreach(['is_default'=>true,'slug'=>'injected','organization_id'=>20] as $key=>$value)$reject(fn()=>$call(array_replace($valid,['fields'=>[$key=>$value]])));
$reject(fn()=>$call($valid+['owner_id'=>20]));
$reject(fn()=>$planController->updatePlan(Illuminate\Http\Request::create('/?owner=20','POST',$valid),(string)$planId));
$state=SaasPlan::findOrFail($planId)->getRawOriginal();$ledger=DB::table('tech4learn_central_requests')->count();
$GLOBALS['failPlanAudit']=true;
try{$call($valid);throw new LogicException('Expected update audit failure');}catch(RuntimeException $e){check($e->getMessage()==='Synthetic native audit failure','Update audit failure propagated');}finally{$GLOBALS['failPlanAudit']=false;}
check(SaasPlan::findOrFail($planId)->getRawOriginal()===$state&&DB::table('tech4learn_central_requests')->count()===$ledger,'Native update and receipt roll back together');
$native=DB::table('tech4learn_central_users')->where('organization_id',10)->where('local_id',$centralActor)->value('external_id');
DB::table('organization_users')->where('organization_id',10)->where('user_id',$native)->update(['status'=>0]);$reject(fn()=>$call($payload));
DB::table('organization_users')->where('organization_id',10)->where('user_id',$native)->update(['status'=>1]);
$plan=SaasPlan::findOrFail($planId);$plan->features=$plan->features+['future_feature'=>true];$plan->save();
$reject($read);$reject(fn()=>$editor->updateForActor(10,$centralActor,$nextId(),$planId,App\Services\Tech4LearnPlanAssignment::revision($plan),['name'=>'Unsafe loss']));
check(SaasPlan::findOrFail($planId)->features['future_feature']===true,'Unknown native settings cannot be silently erased');
$catalogue=$planController->centralPlans(Illuminate\Http\Request::create('/','GET'));
check(count(array_filter($catalogue['items'],fn($item)=>$item['id']===$planId&&!$item['active']))===1,'Central catalogue includes inactive plans for management');
$reject(fn()=>$planController->centralPlans(Illuminate\Http\Request::create('/?after=-1','GET')));
$plan=SaasPlan::findOrFail($planId);$features=$plan->features;unset($features['future_feature']);$plan->features=$features;$plan->is_default=true;$plan->save();
$editor->updateForActor(10,$centralActor,$nextId(),$planId,App\Services\Tech4LearnPlanAssignment::revision($plan->fresh()),['status'=>true]);
check(SaasPlan::findOrFail($planId)->is_default&&SaasPlan::where('id','!=',$planId)->where('is_default',true)->count()===0,'Native edit preserves the existing global default');
for($i=0;$i<51;$i++)SaasPlan::create(['name'=>'Synthetic page '.$i,'slug'=>'page-'.$i,'status'=>false,'is_default'=>false]);
$first=$planController->centralPlans(Illuminate\Http\Request::create('/','GET'));
$second=$planController->centralPlans(Illuminate\Http\Request::create('/?after='.$first['next'],'GET'));
check(count($first['items'])===50&&$second['next']===null&&count(array_unique(array_column(array_merge($first['items'],$second['items']),'id')))===SaasPlan::count(),'Central plan catalogue includes active and inactive rows in bounded non-overlapping pages');
echo "Native plan editing: snapshot, partial native updates, scope, retry, revision conflict, audit rollback, preserved assignments and unknown-setting protection passed.\n";
