<?php
// Native controller and synthetic SQLite only; no application bootstrap.
require __DIR__.'/test-exam-authoring.php';
if(isset($argv[3]))require dirname($argv[3]).'/PassageController.php';
use Illuminate\Support\Facades\DB;
use App\Models\{Passage,PassageLang,Language};
if(!DB::getSchemaBuilder()->hasColumn('passage_langs','passage'))DB::statement('ALTER TABLE passage_langs ADD COLUMN passage TEXT');
foreach(['index'=>'passages','create'=>'passages/create','edit'=>'passages/{passage}/edit'] as $name=>$path)$routes->add((new Illuminate\Routing\Route(['GET'],$path,fn()=>null))->name('passages.'.$name));
DB::table('tech4learn_workspaces')->where('id',$workspace)->update(['restrictions'=>'[]']);
$lang=Language::create(['organization_id'=>20,'name'=>'Passage fixture language','code'=>'px','is_enabled'=>true]);
$next=fn()=>sprintf('%s-%s-4%s-a%s-%s',bin2hex(random_bytes(4)),bin2hex(random_bytes(2)),substr(bin2hex(random_bytes(2)),1),substr(bin2hex(random_bytes(2)),1),bin2hex(random_bytes(6)));
$request=$next();$fields=['name'=>'Synthetic passage authoring','passages'=>[$lang->id=>'<p>Two pairs make four.</p>']];
$saved=$service->save($workspace,20,$actor,0,$fields,'new',$request,'passages');
check((int)Passage::findOrFail($saved['id'])->organization_id===20&&str_contains($saved['fields']['passages'][$lang->id],'Two pairs'),'Native passage controller saves owned translated wording');
check($service->save($workspace,20,$actor,0,$fields,'new',$request,'passages')===$saved,'Identical passage retry returns one saved record');
$questionBefore=$service->snapshot($q->fresh());
$linked=$service->save($workspace,20,$actor,$q->id,['passage_id'=>$saved['id']],$questionBefore['revision'],$next());
check((int)$linked['fields']['passage_id']===$saved['id'],'Native question authoring attaches the owned passage');
$source=App\Models\Question::create(['organization_id'=>20,'question'=>'Synthetic passage reference','passage_id'=>$saved['id']]);
$invalidationBefore=App\Services\ExamDocumentInvalidationService::$questionCalls;
$updated=$service->save($workspace,20,$actor,$saved['id'],['passages'=>[$lang->id=>'<p>Updated wording</p>']],$saved['revision'],$next(),'passages');
check($updated['revision']!==$saved['revision']&&str_contains($updated['fields']['passages'][$lang->id],'Updated wording'),'Passage wording changes the concurrency revision');
check(App\Services\ExamDocumentInvalidationService::$questionCalls===$invalidationBefore+2,'Both referenced sources invoke native document invalidation');
$reject=function(callable $operation,int $status){try{$operation();throw new RuntimeException('Expected passage rejection');}catch(Illuminate\Database\Eloquent\ModelNotFoundException $error){check($status===404,'Passage ownership rejection');}catch(Illuminate\Validation\ValidationException $error){check($status===422,'Passage validation rejection');}catch(Symfony\Component\HttpKernel\Exception\HttpExceptionInterface $error){check($error->getStatusCode()===$status,'Passage rejection status');}};
$reject(fn()=>$service->save($workspace,20,$actor,$saved['id'],['name'=>'Stale edit'],$saved['revision'],$next(),'passages'),409);
$foreign=Passage::create(['organization_id'=>10,'name'=>'Foreign passage fixture']);
$reject(fn()=>$service->save($workspace,20,$actor,$q->id,['passage_id'=>$foreign->id],$linked['revision'],$next()),422);
check((int)$q->fresh()->passage_id===$saved['id'],'Foreign passage attachment leaves the owned reference unchanged');
$reject(fn()=>$service->save($workspace,20,$actor,$foreign->id,['name'=>'Wrong owner'],'new',$next(),'passages'),404);
$reject(fn()=>$service->save($workspace,20,$actor,$saved['id'],['passages'=>['01'=>'Invalid language key']],$updated['revision'],$next(),'passages'),422);
$reject(fn()=>$service->save($workspace,20,$actor,$saved['id'],['passages'=>[$lang->id=>'<img src="https://synthetic.invalid/private.png">']],$updated['revision'],$next(),'passages'),422);
DB::table('tech4learn_workspaces')->where('id',$workspace)->update(['restrictions'=>'["questions"]']);
$reject(fn()=>$service->save($workspace,20,$actor,0,$fields,'new',$request,'passages'),403);
check(Passage::where('name',$fields['name'])->count()===1,'Failed passage writes create no duplicates');
DB::statement('CREATE TABLE tech4learn_central_users(organization_id INTEGER,local_id TEXT,external_id INTEGER UNIQUE,PRIMARY KEY(organization_id,local_id))');
DB::statement('CREATE TABLE tech4learn_central_requests(organization_id INTEGER,request_id TEXT,actor_id TEXT,fingerprint TEXT,result TEXT,created_at TEXT,PRIMARY KEY(organization_id,request_id))');
foreach(['username','email','password','ugroup_id','is_platform_admin','created_at','updated_at'] as $column)DB::statement('ALTER TABLE users ADD COLUMN '.$column.' TEXT');
foreach(['role','created_at','updated_at'] as $column)DB::statement('ALTER TABLE organization_users ADD COLUMN '.$column.' TEXT');
$app['config']->set('hashing',['driver'=>'bcrypt','bcrypt'=>['rounds'=>4]]);
$app->instance('hash',new Illuminate\Hashing\HashManager($app));
Illuminate\Support\Facades\Hash::clearResolvedInstance('hash');
$centralActor=$next();$centralLanguage=Language::create(['organization_id'=>10,'name'=>'Central passage language','code'=>'cp','is_enabled'=>true]);
$secondLanguage=Language::create(['organization_id'=>10,'name'=>'Second passage language','code'=>'sp','is_enabled'=>true]);
$centralFields=['name'=>'Synthetic central passage','passages'=>[$centralLanguage->id=>'<p>Central wording</p>',$secondLanguage->id=>'<p>Preserved wording</p>']];
$key=$next();$central=$service->saveCentralTaxonomy(10,$centralActor,'passages',0,$centralFields,'new',$key);
check((int)Passage::findOrFail($central['id'])->organization_id===10,'Central passage belongs to central owner');
check($service->saveCentralTaxonomy(10,$centralActor,'passages',0,$centralFields,'new',$key)===$central,'Central exact retry is idempotent');
$centralUpdated=$service->saveCentralTaxonomy(10,$centralActor,'passages',$central['id'],['passages'=>[$centralLanguage->id=>'<p>Central edit</p>']],$central['revision'],$next());
check(str_contains($centralUpdated['fields']['passages'][$secondLanguage->id],'Preserved wording'),'Editing one passage language preserves the other');
check($service->record('passages',Passage::findOrFail($saved['id']))===$updated,'Central editing preserves organisation passage');
$reject(fn()=>$service->saveCentralTaxonomy(10,$centralActor,'passages',$saved['id'],['name'=>'Foreign edit'],$updated['revision'],$next()),404);
$reject(fn()=>$service->saveCentralTaxonomy(10,$centralActor,'passages',$central['id'],['passages'=>[$lang->id=>'Wrong owner language']],$centralUpdated['revision'],$next()),422);
$nativeActor=DB::table('tech4learn_central_users')->where('local_id',$centralActor)->value('external_id');
require __DIR__.'/Tech4LearnContentController.php';
$centralController=new class extends App\Http\Controllers\Tech4LearnContentController {
 protected function configuration(Illuminate\Http\Request $r):array{return ['_platform'=>['organization_id'=>10]];}
 protected function reply(int $owner,array $data){return $data;}
};
$read=$centralController->centralTaxonomy(Illuminate\Http\Request::create('/','GET'),'passages',(string)$central['id']);
check($read['record']===$centralUpdated,'Private central passage read returns owned revision and wording');
$body=['actor_id'=>$centralActor,'request_id'=>$next(),'revision'=>$centralUpdated['revision'],'fields'=>['name'=>'Central route rename']];
$reply=$centralController->centralTaxonomyWrite(Illuminate\Http\Request::create('/','POST',$body),'passages',(string)$central['id']);
check($reply['saved']&&$reply['record']['fields']['name']==='Central route rename','Private central passage write uses native controller');
check($centralController->centralTaxonomyWrite(Illuminate\Http\Request::create('/','POST',$body),'passages',(string)$central['id'])===$reply,'Private route retries preserve receipt');
$choices=$controller->centralChoices(Illuminate\Http\Request::create('/','GET'),'passages');
check(in_array($central['id'],array_column($choices['items'],'id'),true)&&!in_array($saved['id'],array_column($choices['items'],'id'),true),'Central passage catalogue excludes organisation records');
$reject(fn()=>$controller->choices(Illuminate\Http\Request::create('/','GET'),$workspace,'passages'),403);
DB::table('organization_users')->where('organization_id',10)->where('user_id',$nativeActor)->update(['status'=>0]);
$reject(fn()=>$service->saveCentralTaxonomy(10,$centralActor,'passages',0,$centralFields,'new',$key),403);
echo "Native passage authoring: both owners, private central routes, scoped catalogue, preserved languages, revisions/retries and revoked access passed. Gateway and interface remain pending.\n";
