<?php
// Native question controller and isolated SQLite data only.
require __DIR__.'/test-central-question-preview.php';
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\{Question,User};

DB::statement('CREATE TABLE tech4learn_central_users(organization_id INTEGER,local_id TEXT,external_id INTEGER UNIQUE,PRIMARY KEY(organization_id,local_id))');
DB::statement('CREATE TABLE tech4learn_central_requests(organization_id INTEGER,request_id TEXT,actor_id TEXT,fingerprint TEXT,result TEXT,created_at TEXT,PRIMARY KEY(organization_id,request_id))');
foreach(['username','email','password','ugroup_id','is_platform_admin','created_at','updated_at'] as $column)DB::statement('ALTER TABLE users ADD COLUMN '.$column.' TEXT');
foreach(['role','created_at','updated_at'] as $column)DB::statement('ALTER TABLE organization_users ADD COLUMN '.$column.' TEXT');
$app['config']->set('hashing',['driver'=>'bcrypt','bcrypt'=>['rounds'=>4]]);
$app->instance('hash',new Illuminate\Hashing\HashManager($app));
Illuminate\Support\Facades\Hash::clearResolvedInstance('hash');
DB::table('tech4learn_workspaces')->where('id',$workspace)->update(['restrictions'=>'[]']);
$centralActor='aaaaaaaa-1111-1111-1111-111111111111';
$nextId=fn()=>(string)Illuminate\Support\Str::uuid();
$centralGroup=App\Models\Group::where('organization_id',10)->firstOrFail();
$centralLanguage=App\Models\Language::where('organization_id',10)->firstOrFail();
$fields=['qtype_id'=>2,'question'=>'New central numerical question','language_id'=>$centralLanguage->id,'group_ids'=>[$centralGroup->id],'nat_mode'=>'exact','nat_value'=>12,'marks'=>4,'status'=>'Yes'];
$body=['actor_id'=>$centralActor,'request_id'=>$nextId(),'revision'=>'new','fields'=>$fields];
$send=function(array $body,string $id='new')use($centralController){
 $response=$centralController->centralWrite(Request::create('/','POST',$body),$id);
 if($response['conflict']??false)abort(409);
 if(!$response['saved'])throw Illuminate\Validation\ValidationException::withMessages($response['errors']);
 return $response['question'];
};
$reject=function(callable $call){try{$call();throw new RuntimeException('Expected central write rejection');}catch(Illuminate\Validation\ValidationException|Illuminate\Database\Eloquent\ModelNotFoundException|Symfony\Component\HttpKernel\Exception\HttpException $e){}};
$count=Question::count();$workspaceCount=DB::table('tech4learn_workspaces')->count();
$createdCentral=$send($body);
check(Question::count()===$count+1&&Question::find($createdCentral['id'])->organization_id==10&&$createdCentral['fields']['nat_value']==12,'Central question created by native controller');
$nativeId=DB::table('tech4learn_central_users')->where('local_id',$centralActor)->value('external_id');
$nativeUser=User::findOrFail($nativeId);
check(!$nativeUser->is_platform_admin&&$nativeUser->status==1&&DB::table('organization_users')->where('user_id',$nativeId)->count()===1&&DB::table('organization_users')->where('user_id',$nativeId)->value('organization_id')==10,'Private author is scoped to the central organisation without global admin');
check(!str_contains(json_encode($createdCentral),$nativeUser->password)&&!str_contains(json_encode($createdCentral),$nativeUser->email),'No native author credentials or account details returned');
check($send($body)===$createdCentral&&DB::table('tech4learn_central_users')->count()===1&&Question::count()===$count+1,'Create replay provisions and creates once');
$copyId=app(App\Services\Tech4LearnContentCopies::class)->copy($workspace,20,'question',$createdCentral['id']);
$copyBefore=Question::findOrFail($copyId)->getAttributes();
$edit=['actor_id'=>$centralActor,'request_id'=>$nextId(),'revision'=>$createdCentral['revision'],'fields'=>['question'=>'<p>Revised central original \\(x^2\\)</p>']];
$updated=$send($edit,(string)$createdCentral['id']);
check($updated['fields']['question']===$edit['fields']['question']&&$updated['fields']['nat_value']==12,'Native central edit preserves answer rules');
check(Question::findOrFail($copyId)->getAttributes()===$copyBefore,'Editing the original leaves an organisation copy unchanged');
check($send($edit,(string)$createdCentral['id'])===$updated,'Central update replay returns original outcome');
$reject(fn()=>$send(array_replace($edit,['fields'=>['question'=>'Changed retry']]),(string)$createdCentral['id']));
$reject(fn()=>$send(array_replace($edit,['request_id'=>$nextId()]),(string)$createdCentral['id']));
$reject(fn()=>$send(array_replace($edit,['request_id'=>$nextId(),'revision'=>$service->snapshot(Question::find($copyId))['revision']]),(string)$copyId));
$usersBefore=User::count();$requestsBefore=DB::table('tech4learn_central_requests')->count();
$badActor='bbbbbbbb-1111-1111-1111-111111111111';
$reject(fn()=>$send(array_replace($body,['actor_id'=>$badActor,'request_id'=>$nextId(),'fields'=>array_replace($fields,['group_ids'=>[$group->id]])])));
check(User::count()===$usersBefore&&DB::table('tech4learn_central_requests')->count()===$requestsBefore&&!DB::table('tech4learn_central_users')->where('local_id',$badActor)->exists(),'Native validation rolls back author provisioning and ledger');
foreach(['organization_id'=>20,'is_platform_admin'=>true,'photo'=>'/etc/passwd'] as $key=>$value)$reject(fn()=>$send(array_replace($body,['request_id'=>$nextId(),'fields'=>$fields+[$key=>$value]])));
$reject(fn()=>$send($body+['organization_id'=>20]));
DB::table('users')->where('id',$nativeId)->update(['status'=>0]);$reject(fn()=>$send($body));
DB::table('users')->where('id',$nativeId)->update(['status'=>1,'is_platform_admin'=>1]);$reject(fn()=>$send($body));
DB::table('users')->where('id',$nativeId)->update(['is_platform_admin'=>0]);
DB::table('organization_users')->where('user_id',$nativeId)->update(['status'=>0]);$reject(fn()=>$send($body));
DB::table('organization_users')->where('user_id',$nativeId)->update(['status'=>1]);
check($send($body)===$createdCentral,'Restored access retains the original create outcome');
$unlinkedSection=App\Models\QuestionSection::create(['organization_id'=>10,'name'=>'Unlinked central section','status'=>1]);
$invalidSection=$centralController->centralWrite(Request::create('/','POST',array_replace($body,['request_id'=>$nextId(),'fields'=>$fields+['question_section_id'=>$unlinkedSection->id]])));
check($invalidSection['saved']===false&&!empty($invalidSection['errors']),'Native relationship validation remains a recoverable field error');
DB::table('organizations')->where('id',10)->update(['status'=>'inactive']);$reject(fn()=>$send($body));
DB::table('organizations')->where('id',10)->update(['status'=>'active']);
$reject(fn()=>$send(array_replace($body,['actor_id'=>$badActor])));
DB::table('tech4learn_central_users')->where('local_id',$centralActor)->delete();$reject(fn()=>$send($body));
check(User::count()===$usersBefore,'Missing mapping on replay does not recreate author access');
check(DB::table('tech4learn_workspaces')->count()===$workspaceCount&&app('request')===$oldRequest&&app('redirect')===$oldRedirect&&$guard->user()===null,'Central saves create no fake workspace and restore native request context');
echo "Central native authoring: owned originals, scoped private actors, validation rollback, independent copies, revocation and retries passed.\n";
