<?php
// Native question controller and isolated SQLite data only.
require __DIR__.'/test-central-question-preview.php';
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Models\{Question,User};

DB::statement('CREATE TABLE tech4learn_central_users(organization_id INTEGER,local_id TEXT,external_id INTEGER UNIQUE,PRIMARY KEY(organization_id,local_id))');
DB::statement('CREATE TABLE tech4learn_central_requests(organization_id INTEGER,request_id TEXT,actor_id TEXT,fingerprint TEXT,result TEXT,created_at TEXT,PRIMARY KEY(organization_id,request_id))');
foreach(['username','email','password','ugroup_id','is_platform_admin','created_at','updated_at'] as $column)DB::statement('ALTER TABLE users ADD COLUMN '.$column.' TEXT');
foreach(['role','created_at','updated_at'] as $column)DB::statement('ALTER TABLE organization_users ADD COLUMN '.$column.' TEXT');
$app['config']->set('hashing',['driver'=>'bcrypt','bcrypt'=>['rounds'=>4]]);
$app->instance('hash',new Illuminate\Hashing\HashManager($app));
Illuminate\Support\Facades\Hash::clearResolvedInstance('hash');
DB::table('tech4learn_workspaces')->where('id',$workspace)->update(['restrictions'=>'[]']);
$centralActor='aaaaaaaa-1111-1111-1111-111111111111';
$nextId=fn()=>(string)Illuminate\Support\Str::uuid();
$centralGroup=App\Models\Group::where('organization_id',10)->firstOrFail();
$centralLanguage=App\Models\Language::where('organization_id',10)->firstOrFail();
$fields=['qtype_id'=>2,'question'=>'New central numerical question','language_id'=>$centralLanguage->id,'group_ids'=>[$centralGroup->id],'nat_mode'=>'exact','nat_value'=>12,'marks'=>4,'status'=>'Yes'];
$body=['actor_id'=>$centralActor,'request_id'=>$nextId(),'revision'=>'new','fields'=>$fields];
$send=function(array $body,string $id='new')use($centralController){
 $response=$centralController->centralWrite(Request::create('/','POST',$body),$id);
 if($response['conflict']??false)abort(409);
 if(!$response['saved'])throw Illuminate\Validation\ValidationException::withMessages($response['errors']);
 return $response['question'];
};
$reject=function(callable $call){try{$call();throw new RuntimeException('Expected central write rejection');}catch(Illuminate\Validation\ValidationException|Illuminate\Database\Eloquent\ModelNotFoundException|Symfony\Component\HttpKernel\Exception\HttpException $e){}};
$count=Question::count();$workspaceCount=DB::table('tech4learn_workspaces')->count();
$createdCentral=$send($body);
check(Question::count()===$count+1&&Question::find($createdCentral['id'])->organization_id==10&&$createdCentral['fields']['nat_value']==12,'Central question created by native controller');
$nativeId=DB::table('tech4learn_central_users')->where('local_id',$centralActor)->value('external_id');
$nativeUser=User::findOrFail($nativeId);
check(!$nativeUser->is_platform_admin&&$nativeUser->status==1&&DB::table('organization_users')->where('user_id',$nativeId)->count()===1&&DB::table('organization_users')->where('user_id',$nativeId)->value('organization_id')==10,'Private author is scoped to the central organisation without global admin');
check(!str_contains(json_encode($createdCentral),$nativeUser->password)&&!str_contains(json_encode($createdCentral),$nativeUser->email),'No native author credentials or account details returned');
check($send($body)===$createdCentral&&DB::table('tech4learn_central_users')->count()===1&&Question::count()===$count+1,'Create replay provisions and creates once');
$copyId=app(App\Services\Tech4LearnContentCopies::class)->copy($workspace,20,'question',$createdCentral['id']);
$copyBefore=Question::findOrFail($copyId)->getAttributes();
$edit=['actor_id'=>$centralActor,'request_id'=>$nextId(),'revision'=>$createdCentral['revision'],'fields'=>['question'=>'<p>Revised central original \\(x^2\\)</p>']];
$updated=$send($edit,(string)$createdCentral['id']);
check($updated['fields']['question']===$edit['fields']['question']&&$updated['fields']['nat_value']==12,'Native central edit preserves answer rules');
check(Question::findOrFail($copyId)->getAttributes()===$copyBefore,'Editing the original leaves an organisation copy unchanged');
check($send($edit,(string)$createdCentral['id'])===$updated,'Central update replay returns original outcome');
$reject(fn()=>$send(array_replace($edit,['fields'=>['question'=>'Changed retry']]),(string)$createdCentral['id']));
$reject(fn()=>$send(array_replace($edit,['request_id'=>$nextId()]),(string)$createdCentral['id']));
$reject(fn()=>$send(array_replace($edit,['request_id'=>$nextId(),'revision'=>$service->snapshot(Question::find($copyId))['revision']]),(string)$copyId));
$usersBefore=User::count();$requestsBefore=DB::table('tech4learn_central_requests')->count();
$badActor='bbbbbbbb-1111-1111-1111-111111111111';
$reject(fn()=>$send(array_replace($body,['actor_id'=>$badActor,'request_id'=>$nextId(),'fields'=>array_replace($fields,['group_ids'=>[$group->id]])])));
check(User::count()===$usersBefore&&DB::table('tech4learn_central_requests')->count()===$requestsBefore&&!DB::table('tech4learn_central_users')->where('local_id',$badActor)->exists(),'Native validation rolls back author provisioning and ledger');
foreach(['organization_id'=>20,'is_platform_admin'=>true,'photo'=>'/etc/passwd'] as $key=>$value)$reject(fn()=>$send(array_replace($body,['request_id'=>$nextId(),'fields'=>$fields+[$key=>$value]])));
$reject(fn()=>$send($body+['organization_id'=>20]));
DB::table('users')->where('id',$nativeId)->update(['status'=>0]);$reject(fn()=>$send($body));
DB::table('users')->where('id',$nativeId)->update(['status'=>1,'is_platform_admin'=>1]);$reject(fn()=>$send($body));
DB::table('users')->where('id',$nativeId)->update(['is_platform_admin'=>0]);
DB::table('organization_users')->where('user_id',$nativeId)->update(['status'=>0]);$reject(fn()=>$send($body));
DB::table('organization_users')->where('user_id',$nativeId)->update(['status'=>1]);
check($send($body)===$createdCentral,'Restored access retains the original create outcome');
$unlinkedSection=App\Models\QuestionSection::create(['organization_id'=>10,'name'=>'Unlinked central section','status'=>1]);
$invalidSection=$centralController->centralWrite(Request::create('/','POST',array_replace($body,['request_id'=>$nextId(),'fields'=>$fields+['question_section_id'=>$unlinkedSection->id]])));
check($invalidSection['saved']===false&&!empty($invalidSection['errors']),'Native relationship validation remains a recoverable field error');
DB::table('organizations')->where('id',10)->update(['status'=>'inactive']);$reject(fn()=>$send($body));
DB::table('organizations')->where('id',10)->update(['status'=>'active']);
$reject(fn()=>$send(array_replace($body,['actor_id'=>$badActor])));
DB::table('tech4learn_central_users')->where('local_id',$centralActor)->delete();$reject(fn()=>$send($body));
check(User::count()===$usersBefore,'Missing mapping on replay does not recreate author access');
check(DB::table('tech4learn_workspaces')->count()===$workspaceCount&&app('request')===$oldRequest&&app('redirect')===$oldRedirect&&$guard->user()===null,'Central saves create no fake workspace and restore native request context');
$centralChoices=$controller->centralChoices(Request::create('/','GET'),'groups');
check(in_array((int)$centralGroup->id,array_column($centralChoices['items'],'id'),true),'Central group choices include central records');
foreach($centralChoices['items'] as $item)check(App\Models\Group::findOrFail($item['id'])->organization_id==10,'Central choices never include organisation groups');
$centralLanguages=$controller->centralChoices(Request::create('/','GET'),'languages');
foreach($centralLanguages['items'] as $item)check(App\Models\Language::findOrFail($item['id'])->organization_id==10,'Central language choices retain native owner scope');
foreach(['types','difficulties','subjects','sections','topics','subtopics'] as $kind)check(is_array($controller->centralChoices(Request::create('/','GET'),$kind)['items']),'Supported central question classification: '.$kind);
foreach([['organization_id'=>'20'],['owner'=>'20'],['parent_id'=>'1'],['after'=>'-1'],['search'=>str_repeat('x',121)]] as $query)$reject(fn()=>$controller->centralChoices(Request::create('/','GET',$query),'groups'));
$reject(fn()=>$controller->centralChoices(Request::create('/','GET'),'platform-languages'));
$reject(fn()=>$controller->centralChoices(Request::create('/','GET'),'packages'));
for($i=0;$i<102;$i++)App\Models\Group::create(['organization_id'=>10,'group_name'=>'Central selector page '.$i]);
$page=$controller->centralChoices(Request::create('/','GET',['search'=>'Central selector page']),'groups');
check(count($page['items'])===100&&$page['next']!==null,'Central choices are bounded and provide a cursor');
$lastPage=$controller->centralChoices(Request::create('/','GET',['search'=>'Central selector page','after'=>(string)$page['next']]),'groups');
check(count($lastPage['items'])===2&&$lastPage['next']===null&&!array_intersect(array_column($page['items'],'id'),array_column($lastPage['items'],'id')),'Central pagination neither repeats nor skips records');
DB::table('organizations')->where('id',10)->update(['status'=>'inactive']);
$reject(fn()=>$controller->centralChoices(Request::create('/','GET'),'groups'));
DB::table('organizations')->where('id',10)->update(['status'=>'active']);
check(DB::table('tech4learn_workspaces')->count()===$workspaceCount,'Central selectors create no tenant workspace');
$imageActor='bbbbbbbb-1111-1111-1111-111111111111';
$imageId=$createdCentral['id'];
$imageSnapshot=fn()=>$service->snapshot(Question::findOrFail($imageId));
$imageSend=function($fields,$revision,$requestId,$id=null)use($centralController,$imageActor,$imageId){
 $response=$centralController->centralImageWrite(Request::create('/','POST',['actor_id'=>$imageActor,'fields'=>$fields,'revision'=>$revision,'request_id'=>$requestId]),(string)($id??$imageId));
 if($response['conflict']??false)abort(409);
 if(!$response['saved'])throw Illuminate\Validation\ValidationException::withMessages($response['errors']);
 return $response['question'];
};
$initialImage=$imageSnapshot();$fileCount=count($imageDisk->files);$writeCount=$imageDisk->writes;
$imageInput=['field'=>'explanation','image'=>substr($imageSource,strpos($imageSource,',')+1)];$imageRequest=$nextId();
$attached=$imageSend($imageInput,$initialImage['revision'],$imageRequest);
check($imageDisk->writes===$writeCount+1&&str_contains($attached['fields']['explanation'],'/storage/images/upload/t4l/10/'),'Central image stored under the credential owner');
check($attached['fields']['nat_value']===$initialImage['fields']['nat_value']&&Question::findOrFail($copyId)->getAttributes()===$copyBefore,'Central image preserves answers and organisation copies');
check($imageSend($imageInput,$initialImage['revision'],$imageRequest)===$attached&&$imageDisk->writes===$writeCount+1,'Central image retry stores only once');
$imageAsset=array_key_first(app(App\Services\Tech4LearnQuestionMedia::class)->sources($attached['fields']['explanation']));
$replacedCentral=$imageSend($imageInput+['asset'=>$imageAsset],$attached['revision'],$nextId());
check(count($imageDisk->files)===$fileCount+2&&substr_count($replacedCentral['fields']['explanation'],'<img')===1,'Central replacement retains potentially shared old files');
$reject(fn()=>$imageSend($imageInput,$initialImage['revision'],$nextId()));
$reject(fn()=>$imageSend($imageInput,$service->snapshot(Question::findOrFail($copyId))['revision'],$nextId(),$copyId));
$reject(fn()=>$imageSend($imageInput+['organization_id'=>20],$replacedCentral['revision'],$nextId()));
$reject(fn()=>$imageSend(array_replace($imageInput,['image'=>'invalid']),$replacedCentral['revision'],$nextId()));
$imageNative=DB::table('tech4learn_central_users')->where('local_id',$imageActor)->value('external_id');
DB::table('users')->where('id',$imageNative)->update(['status'=>0]);$reject(fn()=>$imageSend($imageInput,$initialImage['revision'],$imageRequest));
DB::table('users')->where('id',$imageNative)->update(['status'=>1]);
$app->instance(App\Http\Controllers\QuestionController::class,new class extends App\Http\Controllers\QuestionController {public function update(Request $request,Question $question){throw new RuntimeException('synthetic central image failure');}});
try{$imageSend($imageInput,$replacedCentral['revision'],$nextId());throw new RuntimeException('Expected image rollback');}catch(RuntimeException $e){check($e->getMessage()==='synthetic central image failure','Native central error propagated');}finally{$app->forgetInstance(App\Http\Controllers\QuestionController::class);}
check(count($imageDisk->files)===$fileCount+2&&$imageSnapshot()===$replacedCentral,'Native failure removes newly stored image and rolls back the record');
$remove=['field'=>'explanation','remove'=>true,'asset'=>array_key_first(app(App\Services\Tech4LearnQuestionMedia::class)->sources($replacedCentral['fields']['explanation']))];$removeRequest=$nextId();
$removedCentral=$imageSend($remove,$replacedCentral['revision'],$removeRequest);
check(!str_contains($removedCentral['fields']['explanation'],'<img')&&count($imageDisk->files)===$fileCount+2,'Central image removal only removes the reference');
check($imageSend($remove,$replacedCentral['revision'],$removeRequest)===$removedCentral,'Central removal replay is stable');
$taxActor='cccccccc-1111-1111-1111-111111111111';
$taxSave=function($kind,$id,$fields,$revision,$request)use($taxActor,$centralController){
 $response=$centralController->centralTaxonomyWrite(Request::create('/','POST',['actor_id'=>$taxActor,'fields'=>$fields,'revision'=>$revision,'request_id'=>$request]),$kind,$id?(string)$id:'new');
 if($response['conflict']??false)abort(409);
 if(!$response['saved'])throw Illuminate\Validation\ValidationException::withMessages($response['errors']);
 check($response['kind']===$kind,'Central write response identifies classification kind');
 return $response['record'];
};
$mappingsBefore=DB::table('tech4learn_central_users')->count();
foreach(['groups','subjects','topics','subtopics','sections'] as $kind){
 $empty=$centralController->centralTaxonomy(Request::create('/','GET'),$kind,'new');
 check($empty['kind']===$kind&&$empty['record']['id']===0&&$empty['record']['revision']==='new','Empty central classification draft: '.$kind);
}
check(DB::table('tech4learn_central_users')->count()===$mappingsBefore,'Reading central draft defaults creates no author');
$groupRequest=$nextId();$groupFields=['group_name'=>'Central authoring group','display_order'=>0];
$taxGroup=$taxSave('groups',0,$groupFields,'new',$groupRequest);
check($taxSave('groups',0,$groupFields,'new',$groupRequest)===$taxGroup,'Central group create replay is stable');
$taxSubject=$taxSave('subjects',0,['subject_name'=>'Central subject','group_ids'=>[$taxGroup['id']],'category_ids'=>[]],'new',$nextId());
$taxTopic=$taxSave('topics',0,['name'=>'Central topic','group_id'=>$taxGroup['id'],'subject_id'=>$taxSubject['id'],'display_order'=>0],'new',$nextId());
$taxSubtopic=$taxSave('subtopics',0,['name'=>'Central subtopic','group_id'=>$taxGroup['id'],'subject_id'=>$taxSubject['id'],'topic_id'=>$taxTopic['id'],'display_order'=>0],'new',$nextId());
$taxSection=$taxSave('sections',0,['name'=>'Central section','group_ids'=>[$taxGroup['id']],'status'=>true],'new',$nextId());
foreach(['groups'=>$taxGroup,'subjects'=>$taxSubject,'topics'=>$taxTopic,'subtopics'=>$taxSubtopic,'sections'=>$taxSection] as $kind=>$record)check($service->owned($kind,10)->whereKey($record['id'])->exists()&&!$service->owned($kind,20)->whereKey($record['id'])->exists(),'Native central classification ownership: '.$kind);
$renamedGroup=$taxSave('groups',$taxGroup['id'],['group_name'=>'Renamed central group'],$taxGroup['revision'],$nextId());
check($centralController->centralTaxonomy(Request::create('/','GET'),'groups',(string)$taxGroup['id'])['record']===$renamedGroup,'Central classification read returns current native revision');
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'groups',(string)$group->id));
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET',['organization_id'=>20]),'groups',(string)$taxGroup['id']));
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'languages','new'));
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'groups','0'));
DB::table('organizations')->where('id',10)->update(['status'=>'inactive']);
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'groups',(string)$taxGroup['id']));
DB::table('organizations')->where('id',10)->update(['status'=>'active']);
check($renamedGroup['fields']['group_name']==='Renamed central group'&&$renamedGroup['fields']['display_order']===0,'Central classification edit preserves other settings');
$reject(fn()=>$taxSave('groups',$taxGroup['id'],['group_name'=>'Stale'],$taxGroup['revision'],$nextId()));
$reject(fn()=>$taxSave('groups',$group->id,['group_name'=>'Foreign'],$service->record('groups',$group->fresh())['revision'],$nextId()));
$reject(fn()=>$taxSave('topics',0,['name'=>'Foreign relationship','group_id'=>$group->id,'subject_id'=>$taxSubject['id']],'new',$nextId()));
$reject(fn()=>$taxSave('groups',0,$groupFields+['organization_id'=>20],'new',$nextId()));
$reject(fn()=>$taxSave('languages',0,['name'=>'Unsupported'],'new',$nextId()));
$taxNative=DB::table('tech4learn_central_users')->where('local_id',$taxActor)->value('external_id');
DB::table('users')->where('id',$taxNative)->update(['status'=>0]);$reject(fn()=>$taxSave('groups',0,$groupFields,'new',$groupRequest));
DB::table('users')->where('id',$taxNative)->update(['status'=>1]);
check($taxSave('groups',0,$groupFields,'new',$groupRequest)===$taxGroup,'Restored central author replays original classification result');
check(DB::table('tech4learn_workspaces')->count()===$workspaceCount,'Central classification authoring creates no tenant workspace');

$orgCategoryBefore=$service->record('categories',App\Models\Category::find($category['id']));
$centralCategoryFields=['title'=>'Central category','status'=>true,'group_ids'=>[$taxGroup['id']],'group_orders'=>[$taxGroup['id']=>4],'meta_title'=>'Retain central metadata'];
$categoryRequest=$nextId();$centralCategory=$taxSave('categories',0,$centralCategoryFields,'new',$categoryRequest);
check($taxSave('categories',0,$centralCategoryFields,'new',$categoryRequest)===$centralCategory,'Central category retry is stable');
$categoryUpdated=$taxSave('categories',$centralCategory['id'],['title'=>'Renamed central category'],$centralCategory['revision'],$nextId());
check($categoryUpdated['fields']['meta_title']==='Retain central metadata'&&(int)$categoryUpdated['fields']['group_orders'][$taxGroup['id']]===4,'Central category edit preserves metadata and group ordering');
$centralSubFields=['title'=>'Central child category','parent_id'=>$centralCategory['id'],'status'=>true];
$subRequest=$nextId();$centralSub=$taxSave('subcategories',0,$centralSubFields,'new',$subRequest);
check($taxSave('subcategories',0,$centralSubFields,'new',$subRequest)===$centralSub,'Central subcategory retry is stable');
$centralSubUpdated=$taxSave('subcategories',$centralSub['id'],['title'=>'Renamed central child'],$centralSub['revision'],$nextId());
check((int)$centralSubUpdated['fields']['parent_id']===$centralCategory['id'],'Central subcategory edit preserves parent');
$reject(fn()=>$taxSave('categories',0,array_replace($centralCategoryFields,['title'=>'Invalid central category','group_ids'=>[$group->id]]),'new',$nextId()));
$reject(fn()=>$taxSave('subcategories',0,array_replace($centralSubFields,['parent_id'=>$category['id']]),'new',$nextId()));
$reject(fn()=>$taxSave('subcategories',0,array_replace($centralSubFields,['parent_id'=>$centralSub['id']]),'new',$nextId()));
$reject(fn()=>$taxSave('categories',$centralCategory['id'],['title'=>'Stale'],$centralCategory['revision'],$nextId()));
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'categories',(string)$category['id']));
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'categories',(string)$centralSub['id']));
$centralCorrupt=App\Models\Category::create(['organization_id'=>10,'title'=>'Invalid cross-owner parent','parent_id'=>$category['id']]);
$reject(fn()=>$centralController->centralTaxonomy(Request::create('/','GET'),'subcategories',(string)$centralCorrupt->id));
$GLOBALS['t4lTestSubcategoriesEnabled']=false;
$ledgerBefore=DB::table('tech4learn_central_requests')->count();
$reject(fn()=>$taxSave('subcategories',0,array_replace($centralSubFields,['title'=>'Disabled child']),'new',$nextId()));
check(DB::table('tech4learn_central_requests')->count()===$ledgerBefore,'Disabled native subcategory setting leaves no central ledger write');
$GLOBALS['t4lTestSubcategoriesEnabled']=true;
$categoryChoices=$controller->centralChoices(Request::create('/','GET'),'categories');
check(in_array($centralCategory['id'],array_column($categoryChoices['items'],'id'),true)&&!in_array($category['id'],array_column($categoryChoices['items'],'id'),true)&&!in_array($centralSub['id'],array_column($categoryChoices['items'],'id'),true),'Central category choices exclude foreign and child categories');
$subChoices=$controller->centralChoices(Request::create('/','GET',['parent_id'=>(string)$centralCategory['id']]),'subcategories');
check(array_column($subChoices['items'],'id')===[$centralSub['id']],'Central subcategory choices use an owned root parent');
$reject(fn()=>$controller->centralChoices(Request::create('/','GET',['parent_id'=>(string)$category['id']]),'subcategories'));
$reject(fn()=>$controller->centralChoices(Request::create('/','GET',['parent_id'=>(string)$centralSub['id']]),'subcategories'));
$reject(fn()=>$controller->centralChoices(Request::create('/','GET',['parent_id'=>'bad']),'subcategories'));
$reject(fn()=>$controller->centralChoices(Request::create('/','GET',['parent_id'=>(string)$centralCategory['id']]),'categories'));
check($service->record('categories',App\Models\Category::find($category['id']))===$orgCategoryBefore,'Central category changes preserve organisation category records');
echo "Central native authoring: originals, actors, classification writes, images, rollback and retries passed.\n";
