/** Native plan flags; availability does not imply an implemented T4L screen. */
export const examPlanFeatures = [
  "public_website",
  "paid_packages",
  "guest_exams",
  "ai_generator",
  "ai_translation",
  "ai_regeneration",
  "ai_content_generation",
  "ai_subjective_analysis",
  "ai_student_analysis",
  "ai_seo",
  "ai_platform_api",
  "ai_settings",
  "email_messaging",
  "sms_messaging",
  "reports",
  "question_sharing",
  "custom_theme",
  "student_self_registration",
  "flashcards",
  "ai_flashcard_generation",
  "exam_quality_audit",
  "exam_quality_source",
  "exam_quality_visual",
  "exam_quality_ai",
] as const;
export const examPlanLimits = [
  "organizations",
  "admins",
  "students",
  "exams",
  "packages",
  "questions",
  "quality_audits_monthly",
  "quality_questions_per_audit",
  "quality_source_per_audit",
  "quality_ai_per_audit",
  "quality_visual_per_audit",
  "quality_repairs_monthly",
] as const;
