<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ApiPDFController extends Controller
{
    public function getQuestions($exam_id)
    {
        $exam = DB::table('exams')->where('id', $exam_id)->first();
        
        if (!$exam) {
            return response()->json(['error' => 'Exam not found'], 404);
        }
        
        $questions = DB::table('questions')
            ->join('exam_questions', 'questions.id', '=', 'exam_questions.question_id')
            ->where('exam_questions.exam_id', $exam_id)
            ->where('questions.status', 'active')
            ->select('questions.*')
            ->orderBy('exam_questions.id')
            ->get();
        
        // Build HTML response
        $html = '<!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"><title>' . htmlspecialchars($exam->name) . '</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .question { margin-bottom: 30px; border-left: 3px solid #0d9488; padding-left: 15px; }
            .options { margin-left: 20px; margin-top: 10px; }
            .option { margin: 5px 0; }
            @media print {
                .no-print { display: none; }
                .question { page-break-inside: avoid; }
            }
        </style>
        </head>
        <body>
            <div style="text-align:center; margin-bottom:30px;">
                <h1>' . htmlspecialchars($exam->name) . '</h1>
                <p>Total Questions: ' . $questions->count() . ' | ' . date('Y-m-d') . '</p>
                <hr>
            </div>';
        
        $counter = 1;
        foreach ($questions as $q) {
            $html .= '<div class="question">';
            $html .= '<h3>Question ' . $counter . '</h3>';
            $html .= '<p>' . nl2br(htmlspecialchars($q->question)) . '</p>';
            $html .= '<div class="options">';
            
            if (!empty($q->option1)) $html .= '<div class="option"><strong>A.</strong> ' . nl2br(htmlspecialchars($q->option1)) . '</div>';
            if (!empty($q->option2)) $html .= '<div class="option"><strong>B.</strong> ' . nl2br(htmlspecialchars($q->option2)) . '</div>';
            if (!empty($q->option3)) $html .= '<div class="option"><strong>C.</strong> ' . nl2br(htmlspecialchars($q->option3)) . '</div>';
            if (!empty($q->option4)) $html .= '<div class="option"><strong>D.</strong> ' . nl2br(htmlspecialchars($q->option4)) . '</div>';
            if (!empty($q->option5)) $html .= '<div class="option"><strong>E.</strong> ' . nl2br(htmlspecialchars($q->option5)) . '</div>';
            
            $html .= '</div></div>';
            $counter++;
        }
        
        $html .= '<div style="text-align:center; margin-top:30px; font-size:12px; color:#666;">Generated by ExamElite</div>';
        $html .= '<div style="text-align:center; margin-top:10px;" class="no-print">';
        $html .= '<button onclick="window.print();" style="padding:10px 20px; background:#0d9488; color:white; border:none; border-radius:5px; cursor:pointer;">📄 Save as PDF</button>';
        $html .= '</div>';
        $html .= '</body></html>';
        
        return response($html)->header('Content-Type', 'text/html');
    }
}
