<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Services\StudentActivityTracker;

class ExamPDFDownloadController extends Controller
{
    public function download($exam_id)
    {
        // Get exam
        $exam = DB::table('exams')->where('id', $exam_id)->first();
        
        if (!$exam) {
            abort(404, 'Exam not found');
        }
        
        // Get questions
        $questions = DB::table('questions')
            ->join('exam_questions', 'questions.id', '=', 'exam_questions.question_id')
            ->where('exam_questions.exam_id', $exam_id)
            ->where('questions.status', 'active')
            ->select('questions.*')
            ->orderBy('exam_questions.id')
            ->get();
        
        if ($questions->isEmpty()) {
            return "No questions found for this exam.";
        }
        
        StudentActivityTracker::trackPdfDownload([
            'organization_id' => $exam->organization_id ?? null,
            'exam_id' => $exam->id,
            'metadata' => ['document_name' => $exam->name, 'document_context' => 'exam_questions', 'delivery' => 'html_print_view'],
        ]);

        // Build HTML output
        $html = '<!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>' . htmlspecialchars($exam->name) . '</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
                .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #0d9488; }
                .exam-title { font-size: 24px; font-weight: bold; color: #0d9488; }
                .question { margin-bottom: 25px; padding: 15px; background: #f9fafb; border-left: 3px solid #0d9488; }
                .question-number { font-weight: bold; color: #0d9488; margin-bottom: 10px; }
                .question-text { margin-bottom: 10px; }
                .options { margin-left: 25px; }
                .option { margin: 5px 0; }
                .footer { text-align: center; margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="exam-title">' . htmlspecialchars($exam->name) . '</div>
                <p>Total Questions: ' . $questions->count() . ' | Duration: ' . ($exam->duration ?? 'N/A') . ' minutes</p>
            </div>';
        
        $counter = 1;
        foreach ($questions as $q) {
            $html .= '<div class="question">';
            $html .= '<div class="question-number">Question ' . $counter . '</div>';
            $html .= '<div class="question-text">' . nl2br(htmlspecialchars($q->question)) . '</div>';
            $html .= '<div class="options">';
            
            if (!empty($q->option1)) $html .= '<div class="option"><strong>A.</strong> ' . nl2br(htmlspecialchars($q->option1)) . '</div>';
            if (!empty($q->option2)) $html .= '<div class="option"><strong>B.</strong> ' . nl2br(htmlspecialchars($q->option2)) . '</div>';
            if (!empty($q->option3)) $html .= '<div class="option"><strong>C.</strong> ' . nl2br(htmlspecialchars($q->option3)) . '</div>';
            if (!empty($q->option4)) $html .= '<div class="option"><strong>D.</strong> ' . nl2br(htmlspecialchars($q->option4)) . '</div>';
            if (!empty($q->option5)) $html .= '<div class="option"><strong>E.</strong> ' . nl2br(htmlspecialchars($q->option5)) . '</div>';
            if (!empty($q->option6)) $html .= '<div class="option"><strong>F.</strong> ' . nl2br(htmlspecialchars($q->option6)) . '</div>';
            
            $html .= '</div>';
            $html .= '</div>';
            $counter++;
        }
        
        $html .= '<div class="footer">Generated by ExamElite | ' . date('Y-m-d H:i:s') . '</div>';
        $html .= '</body></html>';
        
        // Return as HTML (for testing)
        return response($html)->header('Content-Type', 'text/html');
    }
}
