<style>
.continuous-pdf-page{position:relative;margin:0 auto 14px;background:#fff;box-shadow:0 2px 10px rgba(15,23,42,.14)}
.continuous-pdf-page img{display:block;width:100%;height:auto}
.continuous-page-label{position:absolute;z-index:2;top:8px;left:8px;padding:3px 8px;border-radius:999px;background:rgba(15,23,42,.78);color:#fff;font-size:.72rem;pointer-events:none}
.continuous-crop-selection{position:absolute;z-index:3;pointer-events:none;border:3px solid #7c3aed;background:rgba(124,58,237,.08);box-shadow:0 0 0 1px rgba(255,255,255,.95),0 2px 8px rgba(15,23,42,.35)}
</style>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const root=document.getElementById('manual-pdf-cropper'); if(!root)return;
    let pageUrl=@json($cropPageUrl),activeEditorSelector=null,nextPage=1,loadingPromise=null,loadGeneration=0,ended=false,saving=false,zoom=1,start=null,activeImage=null,activeWrap=null,selectionStart=0,selectionEnd=0,recognition=null;
    const targets=@json($targetCandidates),form=document.getElementById('manual-crop-form'),stage=document.getElementById('source-crop-stage'),pages=document.getElementById('continuous-source-pages');
    const pageInput=document.getElementById('crop-page'),targetInput=document.getElementById('crop-target-field'),nextTarget=document.getElementById('crop-next-target'),targetLabel=document.getElementById('crop-current-target'),modeInput=document.getElementById('crop-operation-mode');
    const roleInput=document.getElementById('crop-source-role'),help=document.getElementById('crop-help'),save=document.getElementById('save-crop'),saveLabel=document.getElementById('save-crop-label');
    const review=document.getElementById('mathpix-review-panel'),recognized=document.getElementById('mathpix-recognized-html'),rendered=document.getElementById('mathpix-rendered-preview'),confidence=document.getElementById('mathpix-confidence'),warning=document.getElementById('mathpix-confidence-warning'),insert=document.getElementById('mathpix-insert');
    const editor=()=>activeEditorSelector?document.querySelector(activeEditorSelector):document.querySelector(`[name="proposed[${targetInput.value}]"], [name="${targetInput.value}"]`);
    const readEditor=field=>field?.id&&window.CKEDITOR?.instances?.[field.id]?window.CKEDITOR.instances[field.id].getData():(field?.value||'');
    const writeEditor=(field,value)=>{if(!field)return;if(field.id&&window.CKEDITOR?.instances?.[field.id])window.CKEDITOR.instances[field.id].setData(value);field.value=value;field.dispatchEvent(new Event('input',{bubbles:true}));};
    const fieldLabel=target=>target==='question'?'Question field':target.startsWith('option')?`Option ${String.fromCharCode(64+Number(target.slice(6)))} field`:'Explanation field';
    const renderMathpix=()=>window.ExamEliteMathPreview.render(rendered,recognized.value);
    const hideReview=()=>{review.classList.add('d-none');recognition=null;};
    const setMode=mode=>{modeInput.value=mode;document.querySelectorAll('.crop-operation-choice').forEach(button=>{const active=button.dataset.cropMode===mode;button.classList.toggle('active',active);button.classList.toggle('btn-primary',active);button.classList.toggle('btn-outline-primary',!active);});hideReview();help.className='alert alert-info py-2 mb-2';help.textContent=mode==='mathpix'?'Mathpix mode selected. Choose a field, then draw tightly around the equation or text. You will preview it before insertion.':'Image mode selected. Choose a field, then draw the image; it will auto-save.';};
    const clearSelection=()=>{pages.querySelectorAll('.continuous-crop-selection').forEach(box=>box.remove());start=activeImage=activeWrap=null;save.disabled=true;['x0','y0','x1','y1'].forEach(name=>document.getElementById('crop-'+name).value='');};
    const sourceUrl=page=>pageUrl+(pageUrl.includes('?')?'&':'?')+'page='+page+(roleInput?'&source_role='+encodeURIComponent(roleInput.value):'');
    const attachSelection=(wrap,image,page)=>{const point=event=>{const rect=image.getBoundingClientRect();return{x:Math.max(0,Math.min(rect.width,event.clientX-rect.left)),y:Math.max(0,Math.min(rect.height,event.clientY-rect.top)),w:rect.width,h:rect.height};};
        wrap.addEventListener('pointerdown',event=>{if(saving)return;if(!activeEditorSelector){help.className='alert alert-warning py-2 mb-2';help.textContent='First select the destination field on the right.';return;}if(!image.complete||!image.naturalWidth)return;clearSelection();hideReview();activeImage=image;activeWrap=wrap;start=point(event);pageInput.value=page;const box=document.createElement('div');box.className='continuous-crop-selection';wrap.appendChild(box);wrap.setPointerCapture(event.pointerId);event.preventDefault();});
        wrap.addEventListener('pointermove',event=>{if(!start||activeWrap!==wrap)return;const p=point(event),box=wrap.querySelector('.continuous-crop-selection'),x=Math.min(start.x,p.x),y=Math.min(start.y,p.y);Object.assign(box.style,{left:x+'px',top:y+'px',width:Math.abs(p.x-start.x)+'px',height:Math.abs(p.y-start.y)+'px'});});
        wrap.addEventListener('pointerup',event=>{if(!start||activeWrap!==wrap)return;const p=point(event),x0=Math.min(start.x,p.x)/p.w,y0=Math.min(start.y,p.y)/p.h,x1=Math.max(start.x,p.x)/p.w,y1=Math.max(start.y,p.y)/p.h;start=null;if(x1-x0<.01||y1-y0<.01){clearSelection();return;}[['x0',x0],['y0',y0],['x1',x1],['y1',y1]].forEach(([name,value])=>document.getElementById('crop-'+name).value=value.toFixed(6));save.disabled=false;help.className='alert alert-info py-2 mb-2';help.textContent=modeInput.value==='mathpix'?'Sending this crop to Mathpix for preview...':'Cropping and saving automatically...';form.requestSubmit();});};
    const loadPage=page=>new Promise(resolve=>{const existing=pages.querySelector(`[data-pdf-page="${page}"]`);if(existing){resolve(existing);return;}const generation=loadGeneration,wrap=document.createElement('div');wrap.className='continuous-pdf-page';wrap.dataset.pdfPage=page;wrap.innerHTML=`<span class="continuous-page-label">Page ${page}</span><div class="p-4 text-center text-muted"><span class="spinner-border spinner-border-sm me-2"></span>Loading page ${page}</div>`;pages.appendChild(wrap);const image=new Image();image.alt=`Private PDF source page ${page}`;image.draggable=false;image.onload=()=>{if(generation!==loadGeneration){resolve(null);return;}wrap.querySelector('div')?.remove();wrap.appendChild(image);attachSelection(wrap,image,page);nextPage=Math.max(nextPage,page+1);help.className='alert alert-success py-2 mb-2';help.textContent='Continuous PDF loaded through page '+page+'. Select a destination field and draw the required region.';resolve(wrap);if(stage.scrollHeight<=stage.clientHeight+200)setTimeout(()=>loadNext(),0);};image.onerror=()=>{if(generation!==loadGeneration){resolve(null);return;}wrap.remove();ended=true;help.className=page===1?'alert alert-danger py-2 mb-2':'alert alert-secondary py-2 mb-2';help.textContent=page===1?'The source PDF could not be displayed.':'All available PDF pages are loaded.';resolve(null);};image.src=sourceUrl(page)+'&t='+Date.now();});
    const loadNext=()=>{if(ended)return Promise.resolve(null);if(loadingPromise)return loadingPromise;const request=loadPage(nextPage);loadingPromise=request;request.finally(()=>{if(loadingPromise===request)loadingPromise=null;});return request;};
    const resetPages=async()=>{loadGeneration++;pages.innerHTML='';nextPage=1;ended=false;loadingPromise=null;clearSelection();hideReview();await loadNext();};
    stage.addEventListener('scroll',()=>{if(!ended&&!loadingPromise&&stage.scrollTop+stage.clientHeight>=stage.scrollHeight-500)loadNext();});
    document.addEventListener('manual-crop-target',event=>{const target=event.detail?.target;if(!targets.includes(target))return;if(event.detail?.cropAction)form.action=event.detail.cropAction;if(event.detail?.pageUrl)pageUrl=event.detail.pageUrl;activeEditorSelector=event.detail?.editorSelector||null;const field=editor();const rawStart=field?.selectionStart??0,rawEnd=field?.selectionEnd??rawStart,fieldEnd=readEditor(field).length;selectionStart=rawEnd>rawStart?rawStart:fieldEnd;selectionEnd=rawEnd>rawStart?rawEnd:fieldEnd;targetInput.value=target;nextTarget.value=target;targetLabel.textContent=fieldLabel(target);saveLabel.textContent='Crop for '+fieldLabel(target);clearSelection();hideReview();help.className='alert alert-info py-2 mb-2';help.textContent=modeInput.value==='mathpix'?fieldLabel(target)+' selected. Draw tightly around the equation/text; preview is required before saving.':fieldLabel(target)+' selected. Draw its exact image; it will save immediately.';});
    document.querySelectorAll('.crop-operation-choice').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.cropMode)));
    document.querySelectorAll('.crop-source-choice').forEach(button=>button.addEventListener('click',async()=>{if(roleInput){roleInput.value=button.dataset.role;button.closest('.dropdown').querySelector('.dropdown-toggle').textContent=button.textContent;}await resetPages();}));
    const applyZoom=()=>{pages.style.width=(zoom*100)+'%';document.getElementById('crop-zoom-reset').textContent=Math.round(zoom*100)+'%';clearSelection();hideReview();};document.getElementById('crop-zoom-in').addEventListener('click',()=>{zoom=Math.min(2.5,zoom+.25);applyZoom();});document.getElementById('crop-zoom-out').addEventListener('click',()=>{zoom=Math.max(.75,zoom-.25);applyZoom();});document.getElementById('crop-zoom-reset').addEventListener('click',()=>{zoom=1;applyZoom();});
    form.addEventListener('submit',async event=>{event.preventDefault();if(!activeEditorSelector||saving)return;saving=true;const savedTarget=targetInput.value,originalLabel=saveLabel.textContent;save.disabled=true;saveLabel.textContent=modeInput.value==='mathpix'?'Recognizing...':'Cropping & auto-saving...';try{const body=new FormData(form);body.set('crop_mode',modeInput.value);const response=await fetch(form.action,{method:'POST',body,headers:{'Accept':'application/json','X-Requested-With':'XMLHttpRequest'},credentials:'same-origin'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||Object.values(result.errors||{})[0]?.[0]||'The crop could not be processed.');if(result.preview_required){recognition=result.recognition;recognized.value=recognition.html||'';confidence.textContent=`Confidence ${recognition.confidence}%`;warning.classList.toggle('d-none',!recognition.low_confidence);review.classList.remove('d-none');await renderMathpix();review.scrollIntoView({behavior:'smooth',block:'nearest'});help.className='alert alert-warning py-2 mb-2';help.textContent='Review every symbol, then insert and save the draft.';return;}const field=editor();if(field&&typeof result.html==='string')writeEditor(field,result.html);document.dispatchEvent(new CustomEvent('manual-crop-saved',{detail:{mode:'image',target:savedTarget,html:result.html,crop:result.crop,editorSelector:activeEditorSelector}}));clearSelection();help.className='alert alert-success py-2 mb-2';help.textContent=result.message||'Crop auto-saved.';}catch(error){help.className='alert alert-danger py-2 mb-2';help.textContent=error.message;save.disabled=false;}finally{saving=false;saveLabel.textContent=originalLabel;}});
    let previewTimer;recognized.addEventListener('input',()=>{clearTimeout(previewTimer);previewTimer=setTimeout(renderMathpix,180);});document.getElementById('mathpix-cancel').addEventListener('click',()=>{hideReview();help.className='alert alert-info py-2 mb-2';help.textContent='Recognition cancelled. Draw again when ready.';});
    insert.addEventListener('click',async()=>{if(!recognition||saving)return;const field=editor();if(!field)return;const insertion=recognized.value,current=readEditor(field),startAt=Math.max(0,Math.min(selectionStart,current.length)),endAt=Math.max(startAt,Math.min(selectionEnd,current.length));const spacer=startAt===endAt&&startAt===current.length&&current.trim()!==''?'\n':'';const merged=current.slice(0,startAt)+spacer+insertion+current.slice(endAt);saving=true;insert.disabled=true;try{const body=new FormData(form);body.set('crop_mode','mathpix');body.set('confirmed','1');body.set('recognized_html',merged);body.set('mathpix_request_id',recognition.request_id||'');body.set('mathpix_confidence',recognition.confidence??0);const response=await fetch(form.action,{method:'POST',body,headers:{'Accept':'application/json','X-Requested-With':'XMLHttpRequest'},credentials:'same-origin'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||'The recognized text could not be saved.');writeEditor(field,result.html);document.dispatchEvent(new CustomEvent('manual-crop-saved',{detail:{mode:'mathpix',target:targetInput.value,html:result.html,editorSelector:activeEditorSelector}}));hideReview();clearSelection();help.className='alert alert-success py-2 mb-2';help.textContent=result.message;}catch(error){help.className='alert alert-danger py-2 mb-2';help.textContent=error.message;}finally{saving=false;insert.disabled=false;}});
    targetLabel.textContent='Select a field on the right';saveLabel.textContent='Select a field and crop';setMode('image');resetPages();
});
</script>