@php
    $confidence = $row['confidence'] ?? 'review';
    $badge = $confidence === 'paired' ? 'success' : ($confidence === 'unmatched-answer' ? 'danger' : 'warning');
@endphp
<tr data-disable-ai-inline>
    <td><input type="hidden" name="rows[{{ $index }}][selected]" value="0"><input type="checkbox" class="form-check-input discovered-paper-checkbox" name="rows[{{ $index }}][selected]" value="1" @checked($row['selected'] ?? false)></td>
    <td><input class="form-control" name="rows[{{ $index }}][exam_name]" value="{{ $row['exam_name'] ?? '' }}" placeholder="Exam name"><span class="badge bg-{{ $badge }} mt-1">{{ str_replace('-', ' ', $confidence) }}</span></td>
    <td><input class="form-control" name="rows[{{ $index }}][year]" value="{{ $row['year'] ?? '' }}" placeholder="2026"></td>
    <td><input class="form-control form-control-sm mb-1" name="rows[{{ $index }}][question_label]" value="{{ $row['question_label'] ?? '' }}" placeholder="Paper name from webpage"><textarea class="form-control" rows="3" name="rows[{{ $index }}][question_url]" placeholder="https://...pdf">{{ $row['question_url'] ?? '' }}</textarea><input type="hidden" name="rows[{{ $index }}][question_local]" value="{{ $row['question_local'] ?? '' }}">@if($row['question_local'] ?? false)<small class="text-success"><i class="ri-file-pdf-line"></i> Local PDF selected</small>@endif</td>
    <td><input class="form-control form-control-sm mb-1" name="rows[{{ $index }}][answer_label]" value="{{ $row['answer_label'] ?? '' }}" placeholder="Key name from webpage"><textarea class="form-control" rows="3" name="rows[{{ $index }}][answer_url]" placeholder="https://...pdf">{{ $row['answer_url'] ?? '' }}</textarea><input type="hidden" name="rows[{{ $index }}][answer_local]" value="{{ $row['answer_local'] ?? '' }}">@if($row['answer_local'] ?? false)<small class="text-success"><i class="ri-file-pdf-line"></i> Local PDF selected</small>@endif</td>
    <td><input class="form-control form-control-sm mb-1" name="rows[{{ $index }}][combined_label]" value="{{ $row['combined_label'] ?? '' }}" placeholder="Combined name from webpage"><textarea class="form-control" rows="3" name="rows[{{ $index }}][combined_url]" placeholder="https://...pdf">{{ $row['combined_url'] ?? '' }}</textarea><input type="hidden" name="rows[{{ $index }}][combined_local]" value="{{ $row['combined_local'] ?? '' }}">@if($row['combined_local'] ?? false)<small class="text-success"><i class="ri-file-pdf-line"></i> Local PDF selected</small>@endif</td>
    <td><select class="form-select discovery-group" name="rows[{{ $index }}][group_id]"><option value="">Use default</option>@foreach($groups as $group)<option value="{{ $group->id }}">{{ $group->group_name }}</option>@endforeach</select></td>
    <td><select class="form-select discovery-category" name="rows[{{ $index }}][category_id]"><option value="">Use default</option></select>@if(user_can_route_action('category.create', 'add'))<input class="form-control mt-1" name="rows[{{ $index }}][new_category]" maxlength="200" placeholder="Or create category" value="{{ $row['new_category'] ?? '' }}"><small class="text-muted">New name overrides category above.</small>@endif</td>
    <td data-subcategory-ui><select class="form-select discovery-subcategory" name="rows[{{ $index }}][subcategory_id]" disabled><option value="">Use default</option></select></td>
    <td><select class="form-select discovery-package" name="rows[{{ $index }}][package_id]"><option value="">Use default</option></select></td>
</tr>
