import 'reflect-metadata';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {migration} from '../dist/schema.js';
import {accessMigration} from '../dist/migration-access.js';
import {learnerMigration} from '../dist/migration-learners.js';
import {configurationMigration} from '../dist/migration-configuration.js';
import {examWorkspaceMigration} from '../dist/migration-exam-workspace.js';
import {createApp} from '../dist/bootstrap.js';
import {ExamEliteService} from '../dist/examelite.service.js';
import {FaceJobsService} from '../dist/face-jobs.service.js';
import {digest} from '../dist/security.js';
import {allPermissions} from '../dist/access-model.js';

test('central question sharing requires superadmin; organisation reads respect modules, scope and restrictions',async()=>{
 const pg=new PGlite();for(const m of [migration,accessMigration,learnerMigration,configurationMigration,examWorkspaceMigration])await pg.exec(m);
 const org=randomUUID(),other=randomUUID(),admin=randomUUID(),member=randomUUID(),role=randomUUID();
 await pg.query("INSERT INTO organisations(id,name,slug) VALUES($1,'Owned','owned'),($2,'Other','other')",[org,other]);
 await pg.query("INSERT INTO users(id,email,name,password_hash,is_superadmin) VALUES($1,'admin@example.test','Admin','unused',true),($2,'member@example.test','Member','unused',false)",[admin,member]);
 await pg.query("INSERT INTO access_roles(id,organisation_id,name,permissions,protected) VALUES($1,$2,'Exam staff',$3,true)",[role,org,allPermissions]);
 await pg.query("INSERT INTO memberships(user_id,organisation_id,role,role_id) VALUES($1,$2,'admin',$3)",[member,org,role]);
 const tokens={};for(const u of [admin,member]){tokens[u]=randomBytes(32).toString('hex');await pg.query("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[digest(tokens[u]),u]);}
 const db={query:(q,p)=>pg.query(q,p),transaction:fn=>pg.transaction(tx=>fn({query:(q,p)=>tx.query(q,p)})),onModuleDestroy:async()=>{}};
 const app=await createApp(undefined,db);app.get(FaceJobsService).onModuleInit=()=>{};
 const remote=app.get(ExamEliteService),requests=[];remote.configuration=async()=>({central:true,organization_id:1,token:'private'});
 remote.request=async(c,o,path,body)=>{requests.push({o,path,body});return path.endsWith('/launch')?{ready:true}:path.endsWith('/transfer')?{count:body.question_ids.length,items:[]}:{items:[],next:null};};
 await app.listen(0,'127.0.0.1');const base=(await app.getUrl())+'/api/v1';
 const call=(path,body,actor=admin,origin='http://localhost:5173')=>fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Cookie:'t4l_session='+tokens[actor],Origin:origin,'Content-Type':'application/json','X-Tech4Learn-Request':'1'},body:body===undefined?undefined:JSON.stringify(body)});
 const platform=`/platform/exam-content/${org}`,own=`/organisations/${org}/exam-content/questions`;
 try{
  assert.equal((await call(platform+'/questions',undefined,member)).status,403);
  assert.equal((await call(own,undefined,member)).status,403);
  assert.equal((await call(`/organisations/${other}/exam-content/questions`,undefined,member)).status,404);
  assert.equal(requests.length,0);
  assert.equal((await call(platform+'/modules',{exams:true,version:0},member)).status,403);
  assert.equal((await call(platform+'/modules',{exams:true,version:0},admin,'https://evil.example')).status,403);
  const enabled=await call(platform+'/modules',{exams:true,version:0});assert.equal(enabled.status,201);assert.equal((await enabled.json()).version,1);
  assert.equal((await call(platform+'/modules',{exams:false,version:0})).status,409);
  assert.equal((await call(own,undefined,member)).status,200);
  assert.match(requests.at(-1).path,/source=organisation/);
  const body={direction:'share',question_ids:[9,2,9],request_id:randomUUID()};
  assert.equal((await call(platform+'/transfer',body,member)).status,403);
  assert.equal((await call(platform+'/transfer',{...body,question_ids:[-1]})).status,400);
  assert.equal((await call(platform+'/transfer',body)).status,201);
  assert.equal(requests.at(-2).body.provision_only,true);
  assert.deepEqual(requests.at(-1).body.question_ids,[2,9]);
  assert.equal(requests.at(-1).body.actor_id,admin);
  assert.equal(JSON.stringify(requests).includes('example.test'),false);
  await pg.query('INSERT INTO examelite_workspaces(organisation_id,restrictions) VALUES($1,$2)',[org,['questions']]);
  assert.equal((await call(own,undefined,member)).status,403);
  assert.equal((await call(platform+'/transfer',body)).status,403);
  assert.equal((await call(platform+'/transfer',{...body,direction:'pull',request_id:randomUUID()})).status,201);
  assert.equal((await call(platform+'/modules',{exams:false,version:1})).status,201);
  assert.equal((await call(own,undefined,member)).status,403);
  assert.equal((await call(`/organisations/${org}/exam-workspace/launch`,{feature:'exams'},member)).status,403);
  assert.equal((await call(platform+'/questions?source=central')).status,200);
 }finally{await app.close();await pg.close();}
});
