import {provisionAttendanceAdministrator} from "../dist/foundation-staff-provision.js";
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {migration} from '../dist/schema.js';
import {accessMigration} from '../dist/migration-access.js';
import {learnerMigration} from '../dist/migration-learners.js';
import {configurationMigration} from '../dist/migration-configuration.js';
import {foundationMigration} from '../dist/migration-foundation.js';
import {foundationPlatformMigration} from '../dist/migration-foundation-platform.js';
import {foundationProvisioningMigration} from '../dist/migration-foundation-provisioning.js';
import {provisionAttendanceOrganisation} from '../dist/foundation-organisation-provision.js';

test('fresh attendance provisioning is idempotent and never adopts old mappings or platform realms',async()=>{
 const pg=new PGlite(),admin=randomUUID(),staff=randomUUID(),old=randomUUID();
 const db={query:(q,p)=>pg.query(q,p),transaction:fn=>pg.transaction(sql=>fn({query:(q,p)=>sql.query(q,p)}))};
 try{
  for(const sql of [migration,accessMigration,learnerMigration,configurationMigration,foundationMigration,foundationPlatformMigration,foundationProvisioningMigration])await pg.exec(sql);
  for(const [id,root] of [[admin,true],[staff,false]])await pg.query('INSERT INTO users(id,email,name,password_hash,is_superadmin) VALUES($1,$2,$3,$4,$5)',[id,id+'@example.invalid','Synthetic','unused',root]);
  await pg.query("INSERT INTO organisations(id,name,slug) VALUES($1,'Synthetic old','native-org-9')",[old]);
  await pg.query('INSERT INTO foundation_platform_staff(native_organisation_id,native_user_id,user_id) VALUES(1,1,$1)',[admin]);
  await assert.rejects(provisionAttendanceOrganisation(db,staff,'2','Synthetic fresh'));
  await assert.rejects(provisionAttendanceOrganisation(db,admin,'1','Synthetic platform'));
  await assert.rejects(provisionAttendanceOrganisation(db,admin,'9','Synthetic old'));
  const interrupted={transaction:fn=>pg.transaction(sql=>fn({query:(q,p)=>{
    if(q.startsWith('INSERT INTO foundation_organisations'))throw new Error('Synthetic organisation-link failure');
    return sql.query(q,p);
  }}))};
  await assert.rejects(provisionAttendanceOrganisation(interrupted,admin,'2','Synthetic fresh'),/organisation-link failure/);
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM organisations WHERE slug='native-org-2'")).rows[0].total,0);
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM audit_events WHERE action='foundation.organisation_provisioned'")).rows[0].total,0);
  assert.equal((await pg.query('SELECT count(*)::integer AS total FROM organisation_settings')).rows[0].total,0);
  assert.equal((await pg.query('SELECT count(*)::integer AS total FROM access_roles')).rows[0].total,0);
  const first=await provisionAttendanceOrganisation(db,admin,'2','Synthetic fresh');
  assert.equal(first.created,true);assert.notEqual(first.organisationId,old);
  assert.deepEqual(await provisionAttendanceOrganisation(db,admin,'2','Synthetic fresh'),{created:false,organisationId:first.organisationId});
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM audit_events WHERE action='foundation.organisation_provisioned'")).rows[0].total,1);
  assert.equal((await pg.query('SELECT count(*)::integer AS total FROM access_roles WHERE organisation_id=$1',[first.organisationId])).rows[0].total>0,true);
  const password='long synthetic provision password';
  await assert.rejects(provisionAttendanceAdministrator(db,staff,'2','22','fresh@example.invalid','Fresh',password));
  await assert.rejects(provisionAttendanceAdministrator(db,admin,'1','22','fresh@example.invalid','Fresh',password));
  await assert.rejects(provisionAttendanceAdministrator(db,admin,'2','22',staff+'@example.invalid','Fresh',password),/never adopted/);
  const failing={transaction:fn=>pg.transaction(sql=>fn({query:(q,p)=>{
    if(q.startsWith('INSERT INTO foundation_staff'))throw new Error('Synthetic staff-link failure');
    return sql.query(q,p);
  }}))};
  await assert.rejects(provisionAttendanceAdministrator(failing,admin,'2','23','rollback@example.invalid','Rollback',password),/staff-link failure/);
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM users WHERE email='rollback@example.invalid'")).rows[0].total,0);
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM memberships WHERE organisation_id=$1",[first.organisationId])).rows[0].total,0);
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM audit_events WHERE action='foundation.staff_provisioned'")).rows[0].total,0);
  const account=await provisionAttendanceAdministrator(db,admin,'2','22','fresh@example.invalid','Fresh',password);
  assert.equal(account.created,true);
  const before=(await pg.query('SELECT password_hash,is_superadmin FROM users WHERE id=$1',[account.userId])).rows[0];
  assert.equal(before.is_superadmin,false);
  assert.deepEqual(await provisionAttendanceAdministrator(db,admin,'2','22','fresh@example.invalid','Fresh','different synthetic password'),{created:false,userId:account.userId});
  assert.equal((await pg.query('SELECT password_hash FROM users WHERE id=$1',[account.userId])).rows[0].password_hash,before.password_hash);
  assert.equal((await pg.query("SELECT count(*)::integer AS total FROM audit_events WHERE action='foundation.staff_provisioned'")).rows[0].total,1);
  await assert.rejects(provisionAttendanceAdministrator(db,admin,'2','22','changed@example.invalid','Fresh',password),/conflicts/);
  await pg.query("UPDATE memberships SET status='suspended' WHERE user_id=$1",[account.userId]);
  await assert.rejects(provisionAttendanceAdministrator(db,admin,'2','22','fresh@example.invalid','Fresh',password),/revoked/);
  assert.equal((await pg.query('SELECT status FROM memberships WHERE user_id=$1',[account.userId])).rows[0].status,'suspended');
  await pg.exec('UPDATE foundation_staff SET active=false WHERE native_organisation_id=2');
  await assert.rejects(provisionAttendanceAdministrator(db,admin,'2','22','fresh@example.invalid','Fresh',password),/revoked/);
  await pg.exec('UPDATE foundation_organisations SET active=false WHERE native_id=2');
  await assert.rejects(provisionAttendanceOrganisation(db,admin,'2','Synthetic fresh'));
  await pg.query('INSERT INTO foundation_organisations(native_id,organisation_id) VALUES(7,$1)',[old]);
  await assert.rejects(provisionAttendanceOrganisation(db,admin,'7','Synthetic old'));
  assert.equal((await pg.query('SELECT name FROM organisations WHERE id=$1',[old])).rows[0].name,'Synthetic old');
 }finally{await pg.close();}
});
